use deku::prelude::*;
use deku::ctx::Endian;
use deku::{ DekuRead, DekuWrite};
#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
#[deku(endian = "endian", ctx = "endian: Endian, version: u32")]
pub struct ATTACK_ELEMENT_CORRECT_PARAM_ST {
	#[deku(bits = 1)]
	pub isDexterityCorrect_byMagic: u8,
	#[deku(bits = 1)]
	pub isStrengthCorrect_byMagic: u8,
	#[deku(bits = 1)]
	pub isLuckCorrect_byPhysics: u8,
	#[deku(bits = 1)]
	pub isFaithCorrect_byPhysics: u8,
	#[deku(bits = 1)]
	pub isMagicCorrect_byPhysics: u8,
	#[deku(bits = 1)]
	pub isDexterityCorrect_byPhysics: u8,
	#[deku(bits = 1)]
	pub isStrengthCorrect_byPhysics: u8,
	#[deku(bits = 1)]
	pub isFaithCorrect_byFire: u8,
	#[deku(bits = 1)]
	pub isMagicCorrect_byFire: u8,
	#[deku(bits = 1)]
	pub isDexterityCorrect_byFire: u8,
	#[deku(bits = 1)]
	pub isStrengthCorrect_byFire: u8,
	#[deku(bits = 1)]
	pub isLuckCorrect_byMagic: u8,
	#[deku(bits = 1)]
	pub isFaithCorrect_byMagic: u8,
	#[deku(bits = 1)]
	pub isMagicCorrect_byMagic: u8,
	#[deku(bits = 1)]
	pub isStrengthCorrect_byDark: u8,
	#[deku(bits = 1)]
	pub isLuckCorrect_byThunder: u8,
	#[deku(bits = 1)]
	pub isFaithCorrect_byThunder: u8,
	#[deku(bits = 1)]
	pub isMagicCorrect_byThunder: u8,
	#[deku(bits = 1)]
	pub isDexterityCorrect_byThunder: u8,
	#[deku(bits = 1)]
	pub isStrengthCorrect_byThunder: u8,
	#[deku(bits = 1)]
	pub isLuckCorrect_byFire: u8,
	#[deku(bits = 7)]
	pub pad1: u8,
	#[deku(bits = 1)]
	pub isLuckCorrect_byDark: u8,
	#[deku(bits = 1)]
	pub isFaithCorrect_byDark: u8,
	#[deku(bits = 1)]
	pub isMagicCorrect_byDark: u8,
	#[deku(bits = 1)]
	pub isDexterityCorrect_byDark: u8,
	pub overwriteStrengthCorrectRate_byPhysics: i16,
	pub overwriteDexterityCorrectRate_byPhysics: i16,
	pub overwriteMagicCorrectRate_byPhysics: i16,
	pub overwriteFaithCorrectRate_byPhysics: i16,
	pub overwriteLuckCorrectRate_byPhysics: i16,
	pub overwriteStrengthCorrectRate_byMagic: i16,
	pub overwriteDexterityCorrectRate_byMagic: i16,
	pub overwriteMagicCorrectRate_byMagic: i16,
	pub overwriteFaithCorrectRate_byMagic: i16,
	pub overwriteLuckCorrectRate_byMagic: i16,
	pub overwriteStrengthCorrectRate_byFire: i16,
	pub overwriteDexterityCorrectRate_byFire: i16,
	pub overwriteMagicCorrectRate_byFire: i16,
	pub overwriteFaithCorrectRate_byFire: i16,
	pub overwriteLuckCorrectRate_byFire: i16,
	pub overwriteStrengthCorrectRate_byThunder: i16,
	pub overwriteDexterityCorrectRate_byThunder: i16,
	pub overwriteMagicCorrectRate_byThunder: i16,
	pub overwriteFaithCorrectRate_byThunder: i16,
	pub overwriteLuckCorrectRate_byThunder: i16,
	pub overwriteStrengthCorrectRate_byDark: i16,
	pub overwriteDexterityCorrectRate_byDark: i16,
	pub overwriteMagicCorrectRate_byDark: i16,
	pub overwriteFaithCorrectRate_byDark: i16,
	pub overwriteLuckCorrectRate_byDark: i16,
	pub InfluenceStrengthCorrectRate_byPhysics: i16,
	pub InfluenceDexterityCorrectRate_byPhysics: i16,
	pub InfluenceMagicCorrectRate_byPhysics: i16,
	pub InfluenceFaithCorrectRate_byPhysics: i16,
	pub InfluenceLuckCorrectRate_byPhysics: i16,
	pub InfluenceStrengthCorrectRate_byMagic: i16,
	pub InfluenceDexterityCorrectRate_byMagic: i16,
	pub InfluenceMagicCorrectRate_byMagic: i16,
	pub InfluenceFaithCorrectRate_byMagic: i16,
	pub InfluenceLuckCorrectRate_byMagic: i16,
	pub InfluenceStrengthCorrectRate_byFire: i16,
	pub InfluenceDexterityCorrectRate_byFire: i16,
	pub InfluenceMagicCorrectRate_byFire: i16,
	pub InfluenceFaithCorrectRate_byFire: i16,
	pub InfluenceLuckCorrectRate_byFire: i16,
	pub InfluenceStrengthCorrectRate_byThunder: i16,
	pub InfluenceDexterityCorrectRate_byThunder: i16,
	pub InfluenceMagicCorrectRate_byThunder: i16,
	pub InfluenceFaithCorrectRate_byThunder: i16,
	pub InfluenceLuckCorrectRate_byThunder: i16,
	pub InfluenceStrengthCorrectRate_byDark: i16,
	pub InfluenceDexterityCorrectRate_byDark: i16,
	pub InfluenceMagicCorrectRate_byDark: i16,
	pub InfluenceFaithCorrectRate_byDark: i16,
	pub InfluenceLuckCorrectRate_byDark: i16,
	#[deku(count = "24")]
	pub pad2: Vec<u8>,
}
