use deku::prelude::*;
use deku::ctx::Endian;
use deku::{ DekuRead, DekuWrite};
#[derive(PartialEq, Debug, DekuRead, DekuWrite)]
#[deku(endian = "endian", ctx = "endian: Endian, version: u32")]
pub struct GAME_SYSTEM_COMMON_PARAM_ST {
	pub baseToughnessRecoverTime: f32,
	pub chrEventTrun_byLeft90: i32,
	pub chrEventTrun_byRight90: i32,
	pub chrEventTrun_byLeft180: i32,
	pub chrEventTrun_byRight180: i32,
	pub chrEventTrun_90TurnStartAngle: i16,
	pub chrEventTrun_180TurnStartAngle: i16,
	pub stealthAtkDamageRate: f32,
	pub flickDamageCutRateSuccessGurad: f32,
	pub npcTalkAnimBeginDiffAngle: f32,
	pub npcTalkAnimEndDiffAngle: f32,
	pub sleepCollectorItemActionButtonParamId: i32,
	pub allowUseBuddyItem_sfxInterval: f32,
	pub allowUseBuddyItem_sfxDmyPolyId: i32,
	pub allowUseBuddyItem_sfxDmyPolyId_horse: i32,
	pub allowUseBuddyItem_sfxId: i32,
	pub onBuddySummon_inActivateRange_sfxInterval: f32,
	pub onBuddySummon_inActivateRange_sfxDmyPolyId: i32,
	pub onBuddySummon_inActivateRange_sfxDmyPolyId_horse: i32,
	pub onBuddySummon_inActivateRange_sfxId: i32,
	pub onBuddySummon_inActivateRange_spEffectId_pc: i32,
	pub onBuddySummon_inWarnRange_spEffectId_pc: i32,
	pub onBuddySummon_atBuddyUnsummon_spEffectId_pc: i32,
	pub onBuddySummon_inWarnRange_spEffectId_buddy: i32,
	pub morningIngameHour: u8,
	pub morningIngameMinute: u8,
	pub morningIngameSecond: u8,
	pub noonIngameHour: u8,
	pub noonIngameMinute: u8,
	pub noonIngameSecond: u8,
	pub nightIngameHour: u8,
	pub nightIngameMinute: u8,
	pub nightIngameSecond: u8,
	pub aiSightRateStart_Morning_Hour: u8,
	pub aiSightRateStart_Morning_Minute: u8,
	pub aiSightRateStart_Noon_Hour: u8,
	pub aiSightRateStart_Noon_Minute: u8,
	pub aiSightRateStart_Evening_Hour: u8,
	pub aiSightRateStart_Evening_Minute: u8,
	pub aiSightRateStart_Night_Hour: u8,
	pub aiSightRateStart_Night_Minute: u8,
	pub aiSightRateStart_Midnight_Hour: u8,
	pub aiSightRateStart_Midnight_Minute: u8,
	pub saLargeDamageHitSfx_Threshold: u8,
	pub saLargeDamageHitSfx_SfxId: i32,
	pub signCreatableDistFromSafePos: f32,
	pub guestResummonDist: f32,
	pub guestLeavingMessageDistMax: f32,
	pub guestLeavingMessageDistMin: f32,
	pub guestLeaveSessionDist: f32,
	pub retryPointAreaRadius: f32,
	pub sleepCollectorSpEffectId: i32,
	pub recoverBelowMaxHpCompletionNoticeSpEffectId: i32,
	pub estusFlaskRecovery_AbsorptionProductionSfxId_byHp: i32,
	pub estusFlaskRecovery_AbsorptionProductionSfxId_byMp: i32,
	pub respawnSpecialEffectActiveCheckerSpEffectId: i32,
	pub onBuddySummon_inActivateRange_spEffectId_buddy: i32,
	pub estusFlaskRecovery_AddEstusTime: f32,
	pub defeatMultiModeEnemyOfSoulCorrectRate_byHost: f32,
	pub defeatMultiModeEnemyOfSoulCorrectRate_byTeamGhost: f32,
	pub defeatMultiModeBossOfSoulCorrectRate_byHost: f32,
	pub defeatMultiModeBossOfSoulCorrectRate_byTeamGhost: f32,
	pub enemyHpGaugeScreenOffset_byUp: i16,
	pub playRegionCollectDist: i16,
	pub enemyDetectionSpEffect_ShootBulletDummypolyId: i16,
	pub bigRuneGreaterDemonBreakInGoodsNum: i16,
	pub bigRuneGreaterDemonBreakInGoodsId: i32,
	pub rideJumpRegionDefaultSfxId: i32,
	pub saAttackRate_forVsRideAtk: f32,
	pub enemySpEffectIdAfterSleepCollectorItemLot: i32,
	pub afterEndingMapUid: i32,
	pub afterEndingReturnPointEntityId: i32,
	pub enemyDetectionSpEffect_BulletId_byCoopRing_RedHunter: i32,
	pub enemyDetectionSpEffect_BulletId_byInvadeOrb_None: i32,
	pub tutorialFlagOnAccessDistView: i32,
	pub tutorialFlagOnAccessRetryPoint: i32,
	pub tutorialFlagOnGetGroupReward: i32,
	pub tutorialFlagOnEnterRideJumpRegion: i32,
	pub tutorialCheckRideJumpRegionExpandRange: f32,
	pub retryPointActivatedPcAnimId: i32,
	pub retryPointActivatedDialogDelayTime: f32,
	pub retryPointActivatedDialogTextId: i32,
	pub signPuddleOpenPcAnimId: i32,
	pub signPuddleOpenDialogDelayTime: f32,
	pub activityOfDeadSpEffect_BulletId: i32,
	pub activityOfDeadSpEffect_ShootBulletDummypolyId: i32,
	pub activityOfDeadSpEffect_DeadFadeOutTime: f32,
	pub ignorNetStateSyncTime_ForThrow: f32,
	pub netPenaltyPointLanDisconnect: i16,
	pub netPenaltyPointProfileSignout: i16,
	pub netPenaltyPointReboot: i16,
	pub netPnaltyPointSuspend: i16,
	pub netPenaltyForgiveItemLimitTime: f32,
	pub netPenaltyPointThreshold: i16,
	pub uncontrolledMoveThresholdTime: i16,
	pub enemyDetectionSpEffect_BulletId_byNpcEnemy: i32,
	pub activityOfDeadTargetSearchSpEffect_OnHitSpEffect: i32,
	pub activityOfDeadTargetSearchSpEffect_MaxLength: f32,
	pub sightRangeLowerPromiseRate: f32,
	pub saLargeDamageHitSfx_MinDamage: i16,
	pub saLargeDamageHitSfx_ForceDamage: i16,
	pub soloBreakInMaxPoint: i32,
	pub npcTalkTimeOutThreshold: f32,
	pub sendPlayLogIntervalTime: f32,
	pub item370_MaxSfxNum: u8,
	pub chrActivateDist_forLeavePC: u8,
	pub summonDataCoopMatchingLevelUpperAbs: i16,
	pub summonDataCoopMatchingLevelUpperRel: i16,
	pub summonDataCoopMatchingWepLevelMul: i16,
	pub pickUpBerserkerSignSpEffectBulletId: i32,
	pub succeedBerserkerSelfKillingEffectId: i32,
	pub machingLevelWhiteSignUpperRel: u8,
	pub machingLevelWhiteSignUpperAbs: u8,
	pub machingLevelRedSignUpperRel: u8,
	pub machingLevelRedSignUpperAbs: u8,
	pub machingWeaponLevelUpperWhiteSign_0: u8,
	pub machingWeaponLevelUpperWhiteSign_1: u8,
	pub machingWeaponLevelUpperWhiteSign_2: u8,
	pub machingWeaponLevelUpperWhiteSign_3: u8,
	pub machingWeaponLevelUpperWhiteSign_4: u8,
	pub machingWeaponLevelUpperWhiteSign_5: u8,
	pub machingWeaponLevelUpperWhiteSign_6: u8,
	pub machingWeaponLevelUpperWhiteSign_7: u8,
	pub machingWeaponLevelUpperWhiteSign_8: u8,
	pub machingWeaponLevelUpperWhiteSign_9: u8,
	pub machingWeaponLevelUpperWhiteSign_10: u8,
	pub machingWeaponLevelUpperRedSign_0: u8,
	pub machingWeaponLevelUpperRedSign_1: u8,
	pub machingWeaponLevelUpperRedSign_2: u8,
	pub machingWeaponLevelUpperRedSign_3: u8,
	pub machingWeaponLevelUpperRedSign_4: u8,
	pub machingWeaponLevelUpperRedSign_5: u8,
	pub machingWeaponLevelUpperRedSign_6: u8,
	pub machingWeaponLevelUpperRedSign_7: u8,
	pub machingWeaponLevelUpperRedSign_8: u8,
	pub machingWeaponLevelUpperRedSign_9: u8,
	pub machingWeaponLevelUpperRedSign_10: u8,
	pub autoInvadePoint_generateDist: u8,
	pub autoInvadePoint_cancelDist: u8,
	pub sendGlobalEventLogIntervalTime: f32,
	pub addSoloBreakInPoint_White: i16,
	pub addSoloBreakInPoint_Black: i16,
	pub addSoloBreakInPoint_ForceJoin: i16,
	pub addSoloBreakInPoint_VisitorGuardian: i16,
	pub addSoloBreakInPoint_VisitorRedHunter: i16,
	pub invincibleTimer_forNetPC_initSync: u8,
	pub invincibleTimer_forNetPC: u8,
	pub redHunter_HostBossAreaGetSoulRate: f32,
	pub ghostFootprintDecalParamId: i32,
	pub leaveAroundHostWarningTime: f32,
	pub hostModeCostItemId: i32,
	pub aIJump_DecelerateParam: f32,
	pub buddyDisappearDelaySec: f32,
	pub aIJump_AnimYMoveCorrectRate_onJumpOff: f32,
	pub stealthSystemSightRate_NotInStealthRigid_NotSightHide_StealthMode: f32,
	pub stealthSystemSightRate_NotInStealthRigid_SightHide_NotStealthMode: f32,
	pub stealthSystemSightRate_NotInStealthRigid_SightHide_StealthMode: f32,
	pub stealthSystemSightRate_InStealthRigid_NotSightHide_NotStealthMode: f32,
	pub stealthSystemSightRate_InStealthRigid_NotSightHide_StealthMode: f32,
	pub stealthSystemSightRate_InStealthRigid_SightHide_NotStealthMode: f32,
	pub stealthSystemSightRate_InStealthRigid_SightHide_StealthMode: f32,
	pub msbEventGeomTreasureInfo_actionButtonParamId_corpse: i32,
	pub msbEventGeomTreasureInfo_itemGetAnimId_corpse: i32,
	pub msbEventGeomTreasureInfo_actionButtonParamId_box: i32,
	pub msbEventGeomTreasureInfo_itemGetAnimId_box: i32,
	pub msbEventGeomTreasureInfo_actionButtonParamId_shine: i32,
	pub msbEventGeomTreasureInfo_itemGetAnimId_shine: i32,
	pub signPuddleAssetId: i32,
	pub signPuddleAppearDmypolyId0: i32,
	pub signPuddleAppearDmypolyId1: i32,
	pub signPuddleAppearDmypolyId2: i32,
	pub signPuddleAppearDmypolyId3: i32,
	pub fallDamageRate_forRidePC: f32,
	pub fallDamageRate_forRideNPC: f32,
	pub OldMonkOfYellow_CreateSignSpEffectId: i32,
	pub StragglerActivateDist: f32,
	pub SpEffectId_EnableUseItem_StragglerActivate: i32,
	pub SpEffectId_StragglerWakeUp: i32,
	pub SpEffectId_StragglerTarget: i32,
	pub SpEffectId_StragglerOppose: i32,
	pub buddyWarp_TriggerTimeRayBlocked: f32,
	pub buddyWarp_TriggerDistToPlayer: f32,
	pub buddyWarp_ThresholdTimePathStacked: f32,
	pub buddyWarp_ThresholdRangePathStacked: f32,
	pub aiSightRate_morning: f32,
	pub aiSightRate_noonA: f32,
	pub buddyPassThroughTriggerTime: f32,
	pub aiSightRate_evening: f32,
	pub aiSightRate_night: f32,
	pub aiSightRate_midnightA: f32,
	#[deku(skip, cond = "version >= 11210015")]
	pub reserve4_2: [u8;4],
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x230: i32,
	pub aiSightRate_sunloss_light: f32,
	pub aiSightRate_sunloss_dark: f32,
	pub aiSightRate_sunloss_veryDark: f32,
	pub stealthSystemSightAngleReduceRate_NotInStealthRigid_NotSightHide_StealthMode: f32,
	pub stealthSystemSightAngleReduceRate_NotInStealthRigid_SightHide_NotStealthMode: f32,
	pub stealthSystemSightAngleReduceRate_NotInStealthRigid_SightHide_StealthMode: f32,
	pub stealthSystemSightAngleReduceRate_InStealthRigid_NotSightHide_NotStealthMode: f32,
	pub stealthSystemSightAngleReduceRate_InStealthRigid_NotSightHide_StealthMode: f32,
	pub stealthSystemSightAngleReduceRate_InStealthRigid_SightHide_NotStealthMode: f32,
	pub stealthSystemSightAngleReduceRate_InStealthRigid_SightHide_StealthMode: f32,
	pub weatherLotConditionStart_Morning_Hour: u8,
	pub weatherLotConditionStart_Morning_Minute: u8,
	pub weatherLotConditionStart_Day_Hour: u8,
	pub weatherLotConditionStart_Day_Minute: u8,
	pub weatherLotConditionStart_Evening_Hour: u8,
	pub weatherLotConditionStart_Evening_Minute: u8,
	pub weatherLotConditionStart_Night_Hour: u8,
	pub weatherLotConditionStart_Night_Minute: u8,
	pub weatherLotConditionStart_DayBreak_Hour: u8,
	pub weatherLotConditionStart_DayBreak_Minute: u8,
	pub weatherLotCondition_reserved: [u8;2],
	pub pclightScaleChangeStart_Hour: u8,
	pub pclightScaleChangeStart_Minute: u8,
	pub pclightScaleChangeEnd_Hour: u8,
	pub pclightScaleChangeEnd_Minute: u8,
	pub pclightScaleByTimezone: f32,
	pub bigRuneGreaterDemon_SummonBuddySpecialEffectId_Buddy: i32,
	pub bigRuneGreaterDemon_SummonBuddySpecialEffectId_Pc: i32,
	pub homeBonfireParamId: i32,
	pub machingWeaponLevelUpperWhiteSign_11: u8,
	pub machingWeaponLevelUpperWhiteSign_12: u8,
	pub machingWeaponLevelUpperWhiteSign_13: u8,
	pub machingWeaponLevelUpperWhiteSign_14: u8,
	pub machingWeaponLevelUpperWhiteSign_15: u8,
	pub machingWeaponLevelUpperWhiteSign_16: u8,
	pub machingWeaponLevelUpperWhiteSign_17: u8,
	pub machingWeaponLevelUpperWhiteSign_18: u8,
	pub machingWeaponLevelUpperWhiteSign_19: u8,
	pub machingWeaponLevelUpperWhiteSign_20: u8,
	pub machingWeaponLevelUpperWhiteSign_21: u8,
	pub machingWeaponLevelUpperWhiteSign_22: u8,
	pub machingWeaponLevelUpperWhiteSign_23: u8,
	pub machingWeaponLevelUpperWhiteSign_24: u8,
	pub machingWeaponLevelUpperWhiteSign_25: u8,
	pub machingWeaponLevelUpperRedSign_11: u8,
	pub machingWeaponLevelUpperRedSign_12: u8,
	pub machingWeaponLevelUpperRedSign_13: u8,
	pub machingWeaponLevelUpperRedSign_14: u8,
	pub machingWeaponLevelUpperRedSign_15: u8,
	pub machingWeaponLevelUpperRedSign_16: u8,
	pub machingWeaponLevelUpperRedSign_17: u8,
	pub machingWeaponLevelUpperRedSign_18: u8,
	pub machingWeaponLevelUpperRedSign_19: u8,
	pub machingWeaponLevelUpperRedSign_20: u8,
	pub machingWeaponLevelUpperRedSign_21: u8,
	pub machingWeaponLevelUpperRedSign_22: u8,
	pub machingWeaponLevelUpperRedSign_23: u8,
	pub machingWeaponLevelUpperRedSign_24: u8,
	pub machingWeaponLevelUpperRedSign_25: u8,
	pub menuTimezoneStart_Morning_Hour: u8,
	pub menuTimezoneStart_Morning_Minute: u8,
	pub menuTimezoneStart_Day1_Hour: u8,
	pub menuTimezoneStart_Day1_Minute: u8,
	pub menuTimezoneStart_Day2_Hour: u8,
	pub menuTimezoneStart_Day2_Minute: u8,
	pub menuTimezoneStart_Evening_Hour: u8,
	pub menuTimezoneStart_Evening_Minute: u8,
	pub menuTimezoneStart_Night_Hour: u8,
	pub menuTimezoneStart_Night_Minute: u8,
	pub menuTimezoneStart_Midnight_Hour: u8,
	pub menuTimezoneStart_Midnight_Minute: u8,
	pub remotePlayerThreatLvNotify_ThreatLv: i16,
	pub remotePlayerThreatLvNotify_NotifyDist: f32,
	pub remotePlayerThreatLvNotify_EndNotifyDist: f32,
	pub worldMapPointDiscoveryExpandRange: f32,
	pub worldMapPointReentryExpandRange: f32,
	pub remotePlayerThreatLvNotify_NotifyTime: i16,
	pub breakIn_A_rebreakInGoodsNum: i16,
	pub breakIn_A_rebreakInGoodsId: i32,
	pub rideJumpoff_SfxId: i32,
	pub rideJumpoff_SfxHeightOffset: f32,
	pub rideJumpoff_SpEffectId: i32,
	pub rideJumpoff_SpEffectIdPc: i32,
	pub unlockExchangeMenuEventFlagId: i32,
	pub unlockMessageMenuEventFlagId: i32,
	pub breakInOnce_A_rebreakInGoodsNum: i16,
	pub breakIn_B_rebreakInGoodsNum: i16,
	pub breakInOnce_A_rebreakInGoodsId: i32,
	pub breakIn_B_rebreakInGoodsId: i32,
	pub actionButtonInputCancelTime: f32,
	pub blockClearBonusDelayTime: f32,
	pub bonfireCheckEnemyRange: f32,
	#[deku(skip, cond = "version >= 10701000", count = "48")]
	pub reserved_124: Vec<u8>,
	#[deku(skip, cond = "version >= 11210015 || version < 10701000", count = "32")]
	pub reserved_1241: Vec<u8>,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x2f0: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x2f4: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x2f8: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x2fc: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x300: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x304: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x308: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x30c: i32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x310: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x314: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x318: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x31c: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x320: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x324: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x328: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x32c: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x330: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x334: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x338: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x33c: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x340: f32,
	#[deku(skip, cond = "version < 10701000")]
	pub unknown_0x344: f32,
	#[deku(skip, cond = "version >= 11210015 || version < 10701000", count = "40")]
	pub pad_0x348: Vec<u8>,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x34c: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x350: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x354: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x358: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x35c: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x360: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x364: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x368: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x36c: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x370: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x374: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x378: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x37c: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x380: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x384: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x388: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x38c: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x390: i32,
	#[deku(skip, cond = "version < 11210015")]
	pub unknown_0x394: i32,
	#[deku(skip, cond = "version < 11210015", count = "108")]
	pub endPad: Vec<u8>,
}
