use std::{collections::HashMap, sync::LazyLock};

pub static ACCESSORY_CAPTION: LazyLock<HashMap<u32, &'static str>> = LazyLock::new(|| {
    HashMap::from([
		(1,""),
		(2,""),
		(100,"Online multiplayer item. Receipt of a plea for<<NEWLINE>>help to the maidens of the Finger Reader.<<NEWLINE>><<NEWLINE>>Summons a Broken Finger Stalker from another<<NEWLINE>>world to face an invading Broken Finger.<<NEWLINE>><<NEWLINE>>Maidens of the Finger Reader speak in hushed<<NEWLINE>>tones about the loathsome, traitorous Broken<<NEWLINE>>Fingers and the dangers of their base invasions."),
		(101,"Online multiplayer item. Record of contract with<<NEWLINE>>the maidens of the Finger Reader.<<NEWLINE>><<NEWLINE>>Be summoned to the world of a player who<<NEWLINE>>has been invaded by a Broken Finger.<<NEWLINE>><<NEWLINE>>The Broken Fingers have betrayed the Finger<<NEWLINE>>Reader. They are a cancer that afflicts the<<NEWLINE>>ties that bind the Tarnished to one another.<<NEWLINE>>They must be excised, and eradicated."),
		(1000,"A medallion with crimson amber inlaid.<<NEWLINE>>Boosts maximum HP.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1001,"A medallion with crimson amber inlaid.<<NEWLINE>>Greatly boosts maximum HP.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1002,"A medallion with crimson amber inlaid.<<NEWLINE>>Vastly boosts maximum HP.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1003,""),
		(1004,""),
		(1005,""),
		(1006,""),
		(1007,""),
		(1008,""),
		(1009,""),
		(1010,"A medallion with cerulean amber inlaid.<<NEWLINE>>Boosts maximum FP.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1011,"A medallion with cerulean amber inlaid.<<NEWLINE>>Greatly boosts maximum FP.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1012,"A medallion with cerulean amber inlaid.<<NEWLINE>>Vastly boosts maximum FP.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1013,""),
		(1014,""),
		(1015,""),
		(1016,""),
		(1017,""),
		(1018,""),
		(1019,""),
		(1020,"A medallion with viridian amber inlaid.<<NEWLINE>>Boosts maximum stamina.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1021,"A medallion with viridian amber inlaid.<<NEWLINE>>Greatly boosts maximum stamina.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1022,"A medallion with viridian amber inlaid.<<NEWLINE>>Vastly boosts maximum stamina.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>A primordial life energy resides inside."),
		(1023,""),
		(1024,""),
		(1025,""),
		(1026,""),
		(1027,""),
		(1028,""),
		(1029,""),
		(1030,"An iron charm that resembles a mass of weaponry.<<NEWLINE>>Boosts maximum equipment load.<<NEWLINE>><<NEWLINE>>This talisman was derived from an unusual greatsword once wielded by a hero hungry for vengeance."),
		(1031,"An iron charm that resembles a mass of weaponry.<<NEWLINE>>Greatly boosts maximum equipment load.<<NEWLINE>><<NEWLINE>>This talisman was derived from an unusual greatsword once wielded by a hero hungry for vengeance."),
		(1032,"A charm that resembles a great jar overflowing with weaponry.<<NEWLINE>>Vastly boosts maximum equipment load.<<NEWLINE>><<NEWLINE>>The great jar grants this talisman to their warriors.<<NEWLINE>>Carry as much as you can—grow big and strong."),
		(1033,""),
		(1034,""),
		(1035,""),
		(1036,""),
		(1037,""),
		(1038,""),
		(1039,""),
		(1040,"A talisman depicting a special blessing of the Erdtree.<<NEWLINE>>Slightly raises maximum HP, stamina, and equip load.<<NEWLINE>><<NEWLINE>>It is said that when the Age of the Erdtree began, such blessings were personally bestowed upon their recipients by Queen Marika herself."),
		(1041,"A talisman depicting a special blessing of the Erdtree.<<NEWLINE>>Raises maximum HP, stamina, and equip load.<<NEWLINE>><<NEWLINE>>It is said that when the Age of the Erdtree began, such blessings were personally bestowed upon their recipients by Queen Marika herself."),
		(1042,"A legendary talisman depicting a special blessing of the Erdtree.<<NEWLINE>><<NEWLINE>>Greatly raises maximum HP, stamina, and equip load.<<NEWLINE>><<NEWLINE>>It is said that when the Age of the Erdtree began, such blessings were personally bestowed upon their recipients by Queen Marika herself."),
		(1043,""),
		(1044,""),
		(1045,""),
		(1046,""),
		(1047,""),
		(1048,""),
		(1049,""),
		(1050,"An eye engraved with an Elden Rune.<<NEWLINE>>Said to be the seal of King Consort Radagon.<<NEWLINE>><<NEWLINE>>Raises vigor, endurance, strength, and dexterity, but also increases damage taken.<<NEWLINE>><<NEWLINE>>These seals represent the lifelong duty of those chosen by the gods."),
		(1051,"This legendary talisman is an eye engraved with an Elden Rune, said to be the seal of King Consort Radagon.<<NEWLINE>><<NEWLINE>>Greatly raises vigor, endurance, strength, and dexterity, but also increases damage taken by a similar measure.<<NEWLINE>><<NEWLINE>>Solemn duty weighs upon the one beholden; not unlike a gnawing curse from which there is no deliverance."),
		(1052,""),
		(1053,""),
		(1054,""),
		(1055,""),
		(1056,""),
		(1057,""),
		(1058,""),
		(1059,""),
		(1060,"A talisman engraved with a scene from a heroic tale.<<NEWLINE>>Raises strength.<<NEWLINE>><<NEWLINE>>The mightiest hero of the demigods confronted the falling stars alone—and thus did he crush them, his conquest sealing the very fate of the stars."),
		(1061,""),
		(1062,""),
		(1063,""),
		(1064,""),
		(1065,""),
		(1066,""),
		(1067,""),
		(1068,""),
		(1069,""),
		(1070,"A talisman engraved with a scene from a heroic tale.<<NEWLINE>>Raises dexterity.<<NEWLINE>><<NEWLINE>>Though born into the accursed rot, when the young girl encountered her mentor and his flowing blade, she gained wings of unparalleled strength."),
		(1071,""),
		(1072,""),
		(1073,""),
		(1074,""),
		(1075,""),
		(1076,""),
		(1077,""),
		(1078,""),
		(1079,""),
		(1080,"A talisman engraved with the legend of a queen.<<NEWLINE>>Raises intelligence.<<NEWLINE>><<NEWLINE>>The young astrologer gazed at the night sky as she walked. She had always chased the stars every step of her journey. Then she met the full moon—and, in time, the astrologer became a queen."),
		(1081,""),
		(1082,""),
		(1083,""),
		(1084,""),
		(1085,""),
		(1086,""),
		(1087,""),
		(1088,""),
		(1089,""),
		(1090,"A talisman engraved with the legend of the Two Fingers.<<NEWLINE>>Raises faith.<<NEWLINE>><<NEWLINE>>Fingers cannot speak, yet these were eloquent.<<NEWLINE>>Persistently did they wriggle, spelling out mysteries in the air.<<NEWLINE>>Thus did we gain the words. The words of our faith."),
		(1091,""),
		(1092,""),
		(1093,""),
		(1094,""),
		(1095,""),
		(1096,""),
		(1097,""),
		(1098,""),
		(1099,""),
		(1100,"A talisman facsimile of a scarab, the carrier of treasures and precious things.<<NEWLINE>><<NEWLINE>>This silver scarab enhances item discovery."),
		(1101,""),
		(1102,""),
		(1103,""),
		(1104,""),
		(1105,""),
		(1106,""),
		(1107,""),
		(1108,""),
		(1109,""),
		(1110,"A talisman facsimile of a scarab, the carrier of treasures and precious things.<<NEWLINE>><<NEWLINE>>This golden scarab increases the amount of runes obtained from defeating enemies."),
		(1140,"This legendary talisman is a treasure of Nokstella, the Eternal City.<<NEWLINE>><<NEWLINE>>Increases memory slots.<<NEWLINE>><<NEWLINE>>This talisman represents the lost black moon.<<NEWLINE>>The moon of Nokstella was the guide of countless stars."),
		(1141,""),
		(1142,""),
		(1143,""),
		(1144,""),
		(1145,""),
		(1146,""),
		(1147,""),
		(1148,""),
		(1149,""),
		(1150,"A talisman in the shape of a green turtle.<<NEWLINE>>Raises stamina recovery speed.<<NEWLINE>><<NEWLINE>>Turtles are known as a nutritious ingredient, symbolic of inexhaustible power.<<NEWLINE>><<NEWLINE>>However, those who hold turtles to be wise creatures consider the practice of eating their meat to be barbarous."),
		(1151,""),
		(1152,""),
		(1153,""),
		(1154,""),
		(1155,""),
		(1156,""),
		(1157,""),
		(1158,""),
		(1159,""),
		(1160,"An accoutrement worn by the ancestral followers.<<NEWLINE>>Raises robustness.<<NEWLINE>>(Robustness governs resistance to blood loss and frost.)<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1161,"An accoutrement worn by the ancestral followers.<<NEWLINE>>Greatly raises robustness.<<NEWLINE>>(Robustness governs resistance to blood loss and frost.)<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1162,""),
		(1163,""),
		(1164,""),
		(1165,""),
		(1166,""),
		(1167,""),
		(1168,""),
		(1169,""),
		(1170,"An accoutrement worn by the ancestral followers.<<NEWLINE>>Raises immunity.<<NEWLINE>>(Immunity governs resistance to poison and rot.)<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1171,"An accoutrement worn by the ancestral followers.<<NEWLINE>>Greatly raises immunity.<<NEWLINE>>(Immunity governs resistance to poison and rot.)<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1172,""),
		(1173,""),
		(1174,""),
		(1175,""),
		(1176,""),
		(1177,""),
		(1178,""),
		(1179,""),
		(1180,"An accoutrement worn by the ancestral followers.<<NEWLINE>>Raises focus.<<NEWLINE>>(Focus governs resistance to sleep and madness.)<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1181,"An accoutrement worn by the ancestral followers.<<NEWLINE>>Greatly raises focus.<<NEWLINE>>(Focus governs resistance to sleep and madness.)<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1182,""),
		(1183,""),
		(1184,""),
		(1185,""),
		(1186,""),
		(1187,""),
		(1188,""),
		(1189,""),
		(1190,"A fetid pustule taken from facial flesh.<<NEWLINE>>Raises vitality.<<NEWLINE>>(Vitality governs resistance to the effects of Death.)<<NEWLINE>><<NEWLINE>>It is said that this pustule came from the visage of the Prince of Death, he who used to be called Godwyn. As First Dead of the demigods, it's said he's buried deep under the capital, at the Erdtree's roots."),
		(1191,"A fetid, overgrown cyst taken from facial flesh.<<NEWLINE>>Greatly raises vitality.<<NEWLINE>>(Vitality governs resistance to the effects of Death.)<<NEWLINE>><<NEWLINE>>It is said that this cyst came from the corrupted visage of one unable to die a true Death. Indeed, it comes from the Prince of Death, scion of the golden bough and First of the Dead among the demigods."),
		(1192,""),
		(1193,""),
		(1194,""),
		(1195,""),
		(1196,""),
		(1197,""),
		(1198,""),
		(1199,""),
		(1200,"A vividly-colored accoutrement precious to the ancestral followers.<<NEWLINE>><<NEWLINE>>Raises immunity, robustness, and focus.<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1201,"A vividly-colored accoutrement precious to the ancestral followers.<<NEWLINE>><<NEWLINE>>Greatly raises immunity, robustness, and focus.<<NEWLINE>><<NEWLINE>>Said to be a budding horn. The ancestral followers believe that the horns of a long-lived beast continue to bud like antlers, over and over again, until the beast one day becomes an ancestral spirit."),
		(1202,""),
		(1203,""),
		(1204,""),
		(1205,""),
		(1206,""),
		(1207,""),
		(1208,""),
		(1209,""),
		(1210,"A talisman depicting the horns of a bull-goat.<<NEWLINE>>Raises poise.<<NEWLINE>><<NEWLINE>>Bull-goats are associated with the stout and mighty Tragoth, said to be unflinching in combat—now a silent comrade to those who fight."),
		(1211,""),
		(1212,""),
		(1213,""),
		(1214,""),
		(1215,""),
		(1216,""),
		(1217,""),
		(1218,""),
		(1219,""),
		(1220,"An eye engraved with an Elden Rune.<<NEWLINE>>Said to be the seal of Queen Marika.<<NEWLINE>><<NEWLINE>>Raises mind, intelligence, faith, and arcane, but also increases damage taken.<<NEWLINE>><<NEWLINE>>These seals represent the lifelong duty of those chosen by the gods."),
		(1221,"This legendary talisman is an eye engraved with an Elden Rune, said to be the seal of Queen Marika.<<NEWLINE>><<NEWLINE>>Greatly raises mind, intelligence, faith, and arcane, but also increases damage taken by a similar measure.<<NEWLINE>><<NEWLINE>>Solemn duty weighs upon the one beholden; not unlike a gnawing curse from which there is no deliverance."),
		(1222,""),
		(1223,""),
		(1224,""),
		(1225,""),
		(1226,""),
		(1227,""),
		(1228,""),
		(1229,""),
		(1230,"Shard of a shattered warrior jar.<<NEWLINE>><<NEWLINE>>Boosts the attack power of skills.<<NEWLINE>><<NEWLINE>>Scraps of stewed flesh cling to the shard, and tatters of ornaments can be seen mingled within the slime. Relics of ancient royal warriors, perhaps."),
		(1231,"Shard of the late Alexander, a shattered warrior jar.<<NEWLINE>><<NEWLINE>>Greatly boosts the attack power of skills.<<NEWLINE>><<NEWLINE>>Scraps of stewed flesh cling to the shard, and tatters of ornaments can be seen mingled within the slime. Relics of a red-haired champion, it would seem."),
		(1232,""),
		(1233,""),
		(1234,""),
		(1235,""),
		(1236,""),
		(1237,""),
		(1238,""),
		(1239,""),
		(1240,""),
		(1241,""),
		(1242,""),
		(1243,""),
		(1244,""),
		(1245,""),
		(1246,""),
		(1247,""),
		(1248,""),
		(1249,""),
		(1250,"Part of the golden prosthesis used by Millicent.<<NEWLINE>>The hand is locked into a fist that once raised a sword aloft.<<NEWLINE>><<NEWLINE>>Boosts dexterity and raises attack power with successive attacks.<<NEWLINE>><<NEWLINE>>The despair of sweet betrayal transformed Millicent from a mere bud into a magnificent flower. And one day, she will be reborn—as a beautiful scarlet valkyrie."),
		(2000,"A talisman carried by assassins who strike unseen.<<NEWLINE>>Patterned on a scorpion freshly shed of its exoskeleton, its claws seizing a heart that shimmers with magic.<<NEWLINE>><<NEWLINE>>Raises magic attack power, but lowers damage negation."),
		(2001,""),
		(2002,""),
		(2003,""),
		(2004,""),
		(2005,""),
		(2006,""),
		(2007,""),
		(2008,""),
		(2009,""),
		(2010,"A talisman carried by assassins who strike unseen.<<NEWLINE>>Patterned on a scorpion freshly shed of its exoskeleton, its claws seizing a heart that sparks with lightning.<<NEWLINE>><<NEWLINE>>Raises lightning attack power, but lowers damage negation."),
		(2011,""),
		(2012,""),
		(2013,""),
		(2014,""),
		(2015,""),
		(2016,""),
		(2017,""),
		(2018,""),
		(2019,""),
		(2020,"A talisman carried by assassins who strike unseen.<<NEWLINE>>Patterned on a scorpion freshly shed of its exoskeleton, its claws seizing a heart that burns with fire.<<NEWLINE>><<NEWLINE>>Raises fire attack power, but lowers damage negation."),
		(2021,""),
		(2022,""),
		(2023,""),
		(2024,""),
		(2025,""),
		(2026,""),
		(2027,""),
		(2028,""),
		(2029,""),
		(2030,"A talisman carried by assassins who strike unseen.<<NEWLINE>>Patterned on a scorpion freshly shed of its exoskeleton, its claws seizing a heart with a blessed glow.<<NEWLINE>><<NEWLINE>>Raises holy attack power, but lowers damage negation."),
		(2031,""),
		(2032,""),
		(2033,""),
		(2034,""),
		(2035,""),
		(2036,""),
		(2037,""),
		(2038,""),
		(2039,""),
		(2040,"A talisman adorned with red feathers, once used in ancient death rituals.<<NEWLINE>>Raises attack power when HP is low.<<NEWLINE>><<NEWLINE>>The heart sings when one draws close to death, and a glorious end awaits those who cling so tenaciously to life."),
		(2041,""),
		(2042,""),
		(2043,""),
		(2044,""),
		(2045,""),
		(2046,""),
		(2047,""),
		(2048,""),
		(2049,""),
		(2050,"A talisman patterned after swords used in ritual combat held to honor the Erdtree.<<NEWLINE>><<NEWLINE>>Raises attack power when HP is at maximum.<<NEWLINE>><<NEWLINE>>The practice had died out by the age of King Consort Radagon, but remains of the arenas where ritual combat took place can still be found in every land."),
		(2051,""),
		(2052,""),
		(2053,""),
		(2054,""),
		(2055,""),
		(2056,""),
		(2057,""),
		(2058,""),
		(2059,""),
		(2060,"A talisman depicting a spear and a soldier.<<NEWLINE>>Enhances the counterattacks that are unique to thrusting weapons.<<NEWLINE>><<NEWLINE>>Spears are standard weapons for soldiers in the Lands Between. They made it possible to respond to a ferocious foe with an equally ferocious counterattack."),
		(2061,""),
		(2062,""),
		(2063,""),
		(2064,""),
		(2065,""),
		(2066,""),
		(2067,""),
		(2068,""),
		(2069,""),
		(2070,"A talisman depicting a hammer and a knight.<<NEWLINE>>Enhances stamina-reducing attacks against a blocking opponent.<<NEWLINE>><<NEWLINE>>Hammers are highly effective against shield-bearing foes, so much so that they are known as 'knight-killers.'"),
		(2071,""),
		(2072,""),
		(2073,""),
		(2074,""),
		(2075,""),
		(2076,""),
		(2077,""),
		(2078,""),
		(2079,""),
		(2080,"A talisman depicting a raised prosthetic blade.<<NEWLINE>>An honor bestowed upon the knights who fought alongside Malenia the Severed.<<NEWLINE>><<NEWLINE>>Raises attack power with successive attacks.<<NEWLINE>><<NEWLINE>>The wings symbolize Malenia and her undefeated prowess. Though she never knew relief from the accursed rot she was born into, her blade was forever beautiful—and relentless."),
		(2081,"A talisman depicting a raised prosthetic blade.<<NEWLINE>>An honor bestowed upon the valkyries who serve the Goddess of Rot.<<NEWLINE>><<NEWLINE>>Greatly raises attack power with successive attacks.<<NEWLINE>><<NEWLINE>>The four sisters were born in the Swamp of Aeonia, and came to the Haligtree under the aegis of Gowry. And yet, those buds were doomed to never blossom."),
		(2082,""),
		(2083,""),
		(2084,""),
		(2085,""),
		(2086,""),
		(2087,""),
		(2088,""),
		(2089,""),
		(2090,"A talisman depicting a dagger and a surgeon.<<NEWLINE>>Enhances critical hits.<<NEWLINE>><<NEWLINE>>The white-garbed field surgeons come to the aid of friend and foe alike by dealing a final deadly thrust to spare them from the prolonged agony of a mortal wound. A sense of mercy is a catalyst for bloodlust."),
		(2091,""),
		(2092,""),
		(2093,""),
		(2094,""),
		(2095,""),
		(2096,""),
		(2097,""),
		(2098,""),
		(2099,""),
		(2100,"A talisman depicting three arrows.<<NEWLINE>>Carried by hunters of beasts.<<NEWLINE>><<NEWLINE>>Increases the effective range of bows."),
		(2101,""),
		(2102,""),
		(2103,""),
		(2104,""),
		(2105,""),
		(2106,""),
		(2107,""),
		(2108,""),
		(2109,""),
		(2110,"A cloth doll depicting a dancer garbed in blue.<<NEWLINE>>An ancient heirloom of some sort.<<NEWLINE>><<NEWLINE>>Raises attack power with lower equipment load.<<NEWLINE>><<NEWLINE>>The dancer in blue represents a fairy, who in legend bestowed a flowing sword upon a blind swordsman. Blade in hand, the swordsman sealed away an ancient god—a god that was Rot itself."),
		(2111,""),
		(2112,""),
		(2113,""),
		(2114,""),
		(2115,""),
		(2116,""),
		(2117,""),
		(2118,""),
		(2119,""),
		(2120,"A talisman depicting a twinblade and a confessor.<<NEWLINE>>Enhances the final hit ending a chain of attacks.<<NEWLINE>><<NEWLINE>>The twinblade technique is a tradition of the confessors, who closely guard the secret of how they preserve the momentum of their attacks. Thus is the final strike of their onslaught all the more deadly."),
		(2121,""),
		(2122,""),
		(2123,""),
		(2124,""),
		(2125,""),
		(2126,""),
		(2127,""),
		(2128,""),
		(2129,""),
		(2130,"A talisman depicting an axe and a warrior.<<NEWLINE>>Enhances charge attacks.<<NEWLINE>><<NEWLINE>>The Lord who led the Long March bore an axe, and his loyal warriors honored him by wielding axes of their own, making them very effective at dealing decisive blows."),
		(2131,""),
		(2132,""),
		(2133,""),
		(2134,""),
		(2135,""),
		(2136,""),
		(2137,""),
		(2138,""),
		(2139,""),
		(2140,"A talisman depicting a lance and a knight.<<NEWLINE>>Enhances attacks while on horseback.<<NEWLINE>><<NEWLINE>>Knights on horseback are deadly foes. They see all below from their lofty position, meeting little meaningful resistance as they charge ahead."),
		(2141,""),
		(2142,""),
		(2143,""),
		(2144,""),
		(2145,""),
		(2146,""),
		(2147,""),
		(2148,""),
		(2149,""),
		(2150,"A talisman depicting three iron arrows.<<NEWLINE>>Carried by soldiers long ago.<<NEWLINE>><<NEWLINE>>Raises attack power of arrows and bolts."),
		(2151,""),
		(2152,""),
		(2153,""),
		(2154,""),
		(2155,""),
		(2156,""),
		(2157,""),
		(2158,""),
		(2159,""),
		(2160,"A talisman depicting the exultation of the Lord of Blood.<<NEWLINE>><<NEWLINE>>Raises attack power when blood loss occurs in the vicinity.<<NEWLINE>><<NEWLINE>>'Render up your offerings of blood to your Lord. Drench my consort's chamber. Slake his cocoon's thirst. His awakening shall herald the dawn of our dynasty.'"),
		(2161,""),
		(2162,""),
		(2163,""),
		(2164,""),
		(2165,""),
		(2166,""),
		(2167,""),
		(2168,""),
		(2169,""),
		(2170,"A talisman depicting the exultation of pests.<<NEWLINE>><<NEWLINE>>Raises attack power when poisoning or rot occurs in the vicinity.<<NEWLINE>><<NEWLINE>>'Rot for the scarlet goddess. O scarlet blossoms, flourish in distant lands, and return to us, the unwanted children.'"),
		(2171,""),
		(2172,""),
		(2173,""),
		(2174,""),
		(2175,""),
		(2176,""),
		(2177,""),
		(2178,""),
		(2179,""),
		(2180,"A talisman depicting a claw and an assassin.<<NEWLINE>>Enhances jump attacks.<<NEWLINE>><<NEWLINE>>The assassins of Ravenmount are killers by trade. They assail their victims while dressed as birds of prey."),
		(2181,""),
		(2182,""),
		(2183,""),
		(2184,""),
		(2185,""),
		(2186,""),
		(2187,""),
		(2188,""),
		(2189,""),
		(2190,"A bronze medallion depicting a roaring giant.<<NEWLINE>>Enhances roars and breath attacks.<<NEWLINE>><<NEWLINE>>In ancient times, the giants were mortal enemies of the Erdtree. Their bellowing roars desolated nature, triggered avalanches, and whipped up storms of flame."),
		(2191,""),
		(2192,""),
		(2193,""),
		(2194,""),
		(2195,""),
		(2196,""),
		(2197,""),
		(2198,""),
		(2199,""),
		(2200,"A talisman depicting a curved sword and a swordsman.<<NEWLINE>>Enhances guard counters.<<NEWLINE>><<NEWLINE>>It is said that a blind swordsman was the originator of this technique—the art of allowing one's opponent to strike so as to leave them vulnerable to a well-timed reply."),
		(2201,""),
		(2202,""),
		(2203,""),
		(2204,""),
		(2205,""),
		(2206,""),
		(2207,""),
		(2208,""),
		(2209,""),
		(2210,"A talisman given by the jars to their friends.<<NEWLINE>>Raises potency of thrown jars.<<NEWLINE>><<NEWLINE>>Though the jars are brought to life by human flesh and blood, they are all rather kindly folk. Perhaps they were made to be better than their innards."),
		(2211,""),
		(2212,""),
		(2213,""),
		(2214,""),
		(2215,""),
		(2216,""),
		(2217,""),
		(2218,""),
		(2219,""),
		(2220,"A talisman depicting a set of perfume bottles.<<NEWLINE>>Raises potency of arts employing perfume.<<NEWLINE>><<NEWLINE>>There are gardens known only to the perfumers. Whether hidden on the fringes of the highlands, or obscured by shadows inside caves, the flowers blossom in secret, waiting to impart their scent."),
		(3000,"A talisman depicting a school of graven mages, the nightmare of the academy.<<NEWLINE>><<NEWLINE>>Raises potency of sorceries.<<NEWLINE>><<NEWLINE>>The primeval current is a forbidden tradition of glintstone sorcery. To those who cleave to its teachings, the act of collecting sorcerers to fashion them into the seeds of stars is but another path of scientific inquiry."),
		(3001,"A talisman depicting the first school of graven mages—a nightmare that would continue to haunt the academy.<<NEWLINE>><<NEWLINE>>Greatly raises potency of sorceries.<<NEWLINE>><<NEWLINE>>The primeval current is a forbidden tradition of glintstone sorcery. To those who cleave to its teachings, the act of collecting sorcerers to fashion them into the seeds of stars is but another path of scientific inquiry."),
		(3040,"A talisman bearing an icon that depicts a group of masked figures.<<NEWLINE>>Raises potency of incantations.<<NEWLINE>><<NEWLINE>>The figures represent the flock at prayer, their firm belief in the intangible inspiring even the solitary founder of their religion.<<NEWLINE>><<NEWLINE>>What is faith if not an affirmation?"),
		(3041,""),
		(3042,""),
		(3043,""),
		(3044,""),
		(3045,""),
		(3046,""),
		(3047,""),
		(3048,""),
		(3049,""),
		(3050,"A talisman bearing an icon that depicts a mass of masked figures.<<NEWLINE>>Greatly raises potency of incantations.<<NEWLINE>><<NEWLINE>>The figures represent the flock at prayer, their firm belief in the intangible inspiring even the solitary founder of their religion.<<NEWLINE>><<NEWLINE>>What is faith if not an affirmation?"),
		(3051,""),
		(3052,""),
		(3053,""),
		(3054,""),
		(3055,""),
		(3056,""),
		(3057,""),
		(3058,""),
		(3059,""),
		(3060,"A legendary talisman depicting the ancient king whose seat lies at the heart of the storm beyond time.<<NEWLINE>><<NEWLINE>>Extends the duration of sorceries and incantations.<<NEWLINE>><<NEWLINE>>It is said that the ancient royal city of Farum Azula has been slowly crumbling since time immemorial."),
		(3061,""),
		(3062,""),
		(3063,""),
		(3064,""),
		(3065,""),
		(3066,""),
		(3067,""),
		(3068,""),
		(3069,""),
		(3070,"A legendary talisman depicting the Elden Lord Radagon.<<NEWLINE>>Shortens the casting time of sorceries and incantations.<<NEWLINE>><<NEWLINE>>As the husband of Rennala of Caria, the red-haired Radagon studied sorcery, and as the husband of Queen Marika, he studied incantations. Thus did the hero aspire to be complete."),
		(3071,""),
		(3072,""),
		(3073,""),
		(3074,""),
		(3075,""),
		(3076,""),
		(3077,""),
		(3078,""),
		(3079,""),
		(3080,"An old glintstone blade that has been stained with blood.<<NEWLINE>><<NEWLINE>>Reduces FP consumption of sorceries and incantations at the cost of maximum HP.<<NEWLINE>><<NEWLINE>>The old sorcerers would slice open their hearts with these blades to imbue a primal glintstone with their soul, and thus did they die."),
		(3081,""),
		(3082,""),
		(3083,""),
		(3084,""),
		(3085,""),
		(3086,""),
		(3087,""),
		(3088,""),
		(3089,""),
		(3090,"A legendary talisman depicting the Elden Lord Godfrey.<<NEWLINE>>Raises charge attack power of sorceries, incantations, and skills.<<NEWLINE>><<NEWLINE>>Godfrey was a ferocious warrior. When he vowed to become a lord, he took the Beast Regent Serosh upon his back to suppress the ceaseless lust for battle that raged within."),
		(4000,"Wrought iron talisman depicting an ancient dragon.<<NEWLINE>>Boosts physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4001,"Wrought iron talisman depicting a duo of ancient dragons.<<NEWLINE>>Greatly boosts physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4002,"Wrought iron talisman depicting a trio of ancient dragons.<<NEWLINE>>Vastly boosts physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4003,"Legendary talisman of wrought iron depicting a massive ancient dragon.<<NEWLINE>>Enormously boosts physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4004,""),
		(4005,""),
		(4006,""),
		(4007,""),
		(4008,""),
		(4009,""),
		(4010,"Talisman depicting a blue ancient dragon.<<NEWLINE>>Boosts magic damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4011,"Talisman depicting a duo of blue ancient dragons.<<NEWLINE>>Greatly boosts magic damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4012,"Talisman depicting a trio of blue ancient dragons.<<NEWLINE>>Vastly boosts magic damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4013,""),
		(4014,""),
		(4015,""),
		(4016,""),
		(4017,""),
		(4018,""),
		(4019,""),
		(4020,"Talisman depicting a red ancient dragon.<<NEWLINE>>Boosts fire damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4021,"Talisman depicting a duo of red ancient dragons.<<NEWLINE>>Greatly boosts fire damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4022,"Talisman depicting a trio of red ancient dragons.<<NEWLINE>>Vastly boosts fire damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4023,""),
		(4024,""),
		(4025,""),
		(4026,""),
		(4027,""),
		(4028,""),
		(4029,""),
		(4030,"Talisman depicting a yellow ancient dragon.<<NEWLINE>>Boosts lightning damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4031,"Talisman depicting a duo of yellow ancient dragons.<<NEWLINE>>Greatly boosts lightning damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4032,"Talisman depicting a trio of yellow ancient dragons.<<NEWLINE>>Vastly boosts lightning damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4033,""),
		(4034,""),
		(4035,""),
		(4036,""),
		(4037,""),
		(4038,""),
		(4039,""),
		(4040,"Talisman depicting a golden ancient dragon.<<NEWLINE>>Boosts holy damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4041,"Talisman depicting a duo of golden ancient dragons.<<NEWLINE>>Greatly boosts holy damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4042,"Talisman depicting a trio of golden ancient dragons.<<NEWLINE>>Vastly boosts holy damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4043,""),
		(4044,""),
		(4045,""),
		(4046,""),
		(4047,""),
		(4048,""),
		(4049,""),
		(4050,"Talisman depicting a pearlescent ancient dragon.<<NEWLINE>>Boosts non-physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4051,"Talisman depicting a duo of pearlescent ancient dragons.<<NEWLINE>>Greatly boosts non-physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4052,"Talisman depicting a trio of pearlescent ancient dragons.<<NEWLINE>>Vastly boosts non-physical damage negation.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(4053,""),
		(4054,""),
		(4055,""),
		(4056,""),
		(4057,""),
		(4058,""),
		(4059,""),
		(4060,"A talisman fashioned from a scale that embodies the aspects of various creatures.<<NEWLINE>>Said to have grown on the human body long ago.<<NEWLINE>><<NEWLINE>>Reduces damage taken from critical hits.<<NEWLINE>><<NEWLINE>>A vestige of the crucible of primordial life. Born partially of devolution, it was considered a signifier of the divine in ancient times, but is now increasingly disdained as an impurity as civilization has advanced."),
		(4061,""),
		(4062,""),
		(4063,""),
		(4064,""),
		(4065,""),
		(4066,""),
		(4067,""),
		(4068,""),
		(4069,""),
		(4070,"A talisman fashioned from feathers that embody the aspects of various creatures.<<NEWLINE>>Said to have grown on the human body long ago.<<NEWLINE>><<NEWLINE>>Improves the effectiveness of dodge rolls, but increases damage taken at all times.<<NEWLINE>><<NEWLINE>>A vestige of the crucible of primordial life. Born partially of devolution, it was considered a signifier of the divine in ancient times, but is now increasingly disdained as an impurity as civilization has advanced."),
		(4071,""),
		(4072,""),
		(4073,""),
		(4074,""),
		(4075,""),
		(4076,""),
		(4077,""),
		(4078,""),
		(4079,""),
		(4080,"A talisman adorned with blue feathers, once used in ancient death rituals.<<NEWLINE>>Raises defense when HP is low.<<NEWLINE>><<NEWLINE>>The heart sings when one draws close to death, and thus does one cling so tenaciously to life—to render up a death worth offering."),
		(4081,""),
		(4082,""),
		(4083,""),
		(4084,""),
		(4085,""),
		(4086,""),
		(4087,""),
		(4088,""),
		(4089,""),
		(4090,"A talisman patterned after shields used in ritual combat held to honor the Erdtree.<<NEWLINE>><<NEWLINE>>Raises defense when HP is at maximum.<<NEWLINE>><<NEWLINE>>The practice had died out by the age of King Consort Radagon, but remains of the arenas where ritual combat took place can still be found in every land."),
		(4091,""),
		(4092,""),
		(4093,""),
		(4094,""),
		(4095,""),
		(4096,""),
		(4097,""),
		(4098,""),
		(4099,""),
		(4100,"Talisman depicting a knight holding a greatshield.<<NEWLINE>>Boosts guarding ability.<<NEWLINE>><<NEWLINE>>The knights of Leyndell once modelled themselves after the Tree Sentinels. Their purpose is to protect that which deserves protection, and thus the shield always comes before the sword."),
		(4101,""),
		(4102,""),
		(4103,""),
		(4104,""),
		(4105,""),
		(4106,""),
		(4107,""),
		(4108,""),
		(4109,""),
		(4110,"A talisman fashioned from a bony knot that embodies the aspects of various creatures.<<NEWLINE>>Said to have grown on the human body long ago.<<NEWLINE>><<NEWLINE>>Reduces damage and impact of headshots taken.<<NEWLINE>><<NEWLINE>>A vestige of the crucible of primordial life. Born partially of devolution, it was considered a signifier of the divine in ancient times, but is now increasingly disdained as an impurity as civilization has advanced."),
		(5000,"A crimson-colored talisman patterned after an Erdtree seed.<<NEWLINE>>Boosts HP restoration from the Flask of Crimson Tears.<<NEWLINE>><<NEWLINE>>The Erdtree was once perfect and eternal, and thus was it believed that Erdtree seeds could not exist."),
		(5001,""),
		(5002,""),
		(5003,""),
		(5004,""),
		(5005,""),
		(5006,""),
		(5007,""),
		(5008,""),
		(5009,""),
		(5010,"A cerulean-colored talisman patterned after an Erdtree seed.<<NEWLINE>>Boosts FP restoration from the Flask of Cerulean Tears.<<NEWLINE>><<NEWLINE>>The Erdtree was once perfect and eternal, and thus was it believed that Erdtree seeds could not exist."),
		(5011,""),
		(5012,""),
		(5013,""),
		(5014,""),
		(5015,""),
		(5016,""),
		(5017,""),
		(5018,""),
		(5019,""),
		(5020,"Talisman depicting a drop of the Erdtree's sap, a blessed boon.<<NEWLINE>><<NEWLINE>>Gradually restores HP.<<NEWLINE>><<NEWLINE>>It was once thought that the blessed sap of the Erdtree would drip from its boughs forever—but that age of plenty swiftly came to a close, and with time, the Erdtree became more an object of faith."),
		(5021,""),
		(5022,""),
		(5023,""),
		(5024,""),
		(5025,""),
		(5026,""),
		(5027,""),
		(5028,""),
		(5029,""),
		(5030,"A talisman engraved with a stern likeness of Praetor Rykard, master of Volcano Manor.<<NEWLINE>><<NEWLINE>>Restores HP upon defeating enemies.<<NEWLINE>><<NEWLINE>>When Rykard turned to heresy, taking by force became the rule. The gods themselves were no different, after all."),
		(5031,""),
		(5032,""),
		(5033,""),
		(5034,""),
		(5035,""),
		(5036,""),
		(5037,""),
		(5038,""),
		(5039,""),
		(5040,"Sacred cloth of the Godskin Apostles, made from supple skin sewn together.<<NEWLINE>><<NEWLINE>>Successive attacks restore HP.<<NEWLINE>><<NEWLINE>>The Gloam-Eyed Queen cradles newborn apostles swaddled in this cloth. Soon they will grow to become the death of the gods."),
		(5041,""),
		(5042,""),
		(5043,""),
		(5044,""),
		(5045,""),
		(5046,""),
		(5047,""),
		(5048,""),
		(5049,""),
		(5050,"An assassin's dagger, misshapen and stained in crimson.<<NEWLINE>>Critical hits restore HP.<<NEWLINE>><<NEWLINE>>This charm is modelled after the darkly gleaming blades used in the Night of Black Knives. Those which gave the demigods their first taste of Death."),
		(5051,""),
		(5052,""),
		(5053,""),
		(5054,""),
		(5055,""),
		(5056,""),
		(5057,""),
		(5058,""),
		(5059,""),
		(5060,"An assassin's dagger, misshapen and stained in cerulean.<<NEWLINE>>Critical hits restore FP.<<NEWLINE>><<NEWLINE>>This charm is modelled after the darkly gleaming blades used in the Night of Black Knives. Those which gave the demigods their first taste of Death."),
		(6000,"Small mysterious bottle with a dark mist sealed within.<<NEWLINE>><<NEWLINE>>Eliminates all sound made by the wearer during movement.<<NEWLINE>><<NEWLINE>>A ritual implement used by Roundtable Hold assassins. There was a time when Tarnished who had strayed from guidance feared nothing more than utter silence."),
		(6001,""),
		(6002,""),
		(6003,""),
		(6004,""),
		(6005,""),
		(6006,""),
		(6007,""),
		(6008,""),
		(6009,""),
		(6010,"Talisman put together from dark cloth with a lustrous sheen.<<NEWLINE>><<NEWLINE>>Completely conceals the wearer's presence while crouching at a distance from foes.<<NEWLINE>><<NEWLINE>>Part of one of the concealing veils used by the assassins on the Night of Black Knives."),
		(6011,""),
		(6012,""),
		(6013,""),
		(6014,""),
		(6015,""),
		(6016,""),
		(6017,""),
		(6018,""),
		(6019,""),
		(6020,"A talisman adorned with the royal crest.<<NEWLINE>><<NEWLINE>>Lowers FP consumed by skills.<<NEWLINE>><<NEWLINE>>An honor said to have once been awarded to Carian knights who served as direct retainers to the kingdom's princesses. Now there is only one princess: Ranni, daughter of Rennala."),
		(6040,"A brooch depicting Lacrima, the long-tailed cat.<<NEWLINE>><<NEWLINE>>Grants immunity to fall damage, but does not prevent death from a high fall.<<NEWLINE>><<NEWLINE>>Lacrima features in the fables of Raya Lucaria, in which she is described as a faerie cat who was fond of playing in the great bell tower."),
		(6041,""),
		(6042,""),
		(6043,""),
		(6044,""),
		(6045,""),
		(6046,""),
		(6047,""),
		(6048,""),
		(6049,""),
		(6050,"Disturbing likeness of a man whose eyes have been gouged out.<<NEWLINE>>The corners of his mouth are upturned in an almost flirtatious manner.<<NEWLINE>><<NEWLINE>>Constantly attracts enemies' aggression.<<NEWLINE>><<NEWLINE>>It is said that the man, named Shabriri, had his eyes gouged out as punishment for the crime of slander, and, with time, the blight of the flame of frenzy came to dwell in the empty sockets."),
		(6051,""),
		(6052,""),
		(6053,""),
		(6054,""),
		(6055,""),
		(6056,""),
		(6057,""),
		(6058,""),
		(6059,""),
		(6060,"Disturbing likeness of a woman whose skin was flayed.<<NEWLINE>>She smiles with a serene tenderness.<<NEWLINE>><<NEWLINE>>Increases damage taken.<<NEWLINE>><<NEWLINE>>It is said that this woman, named Daedicar, indulged in every form of adultery and wicked pleasure imaginable, giving birth to a myriad of grotesque children."),
		(6061,""),
		(6062,""),
		(6063,""),
		(6064,""),
		(6065,""),
		(6066,""),
		(6067,""),
		(6068,""),
		(6069,""),
		(6070,"A talisman fashioned from a dried twig, so slender that it might snap at the slightest touch.<<NEWLINE>><<NEWLINE>>Prevents rune loss upon death, but will be lost itself in exchange.<<NEWLINE>><<NEWLINE>>Believed to be a twig pruned from the Erdtree long, long ago."),
		(6071,""),
		(6072,""),
		(6073,""),
		(6074,""),
		(6075,""),
		(6076,""),
		(6077,""),
		(6078,""),
		(6079,""),
		(6080,"A small, clouded mirror that reflects an image of a golden figure.<<NEWLINE>><<NEWLINE>>Makes the bearer take on the appearance of a Host of Fingers.<<NEWLINE>><<NEWLINE>>One of the ritual implements created by the Tarnished to deceive invaders."),
		(6081,""),
		(6082,""),
		(6083,""),
		(6084,""),
		(6085,""),
		(6086,""),
		(6087,""),
		(6088,""),
		(6089,""),
		(6090,"A small, clouded mirror that reflects a flesh-and-blood figure.<<NEWLINE>><<NEWLINE>>Makes the bearer take on the appearance of a summoned cooperator.<<NEWLINE>><<NEWLINE>>One of the ritual implements created by the Tarnished to deceive invaders."),
		(6091,""),
		(6092,""),
		(6093,""),
		(6094,""),
		(6095,""),
		(6096,""),
		(6097,""),
		(6098,""),
		(6099,""),
		(6100,"Mysterious circular object that's oddly warped.<<NEWLINE>>Changes the demeanour of the wearer's actions."),
		(6101,""),
		(6102,""),
		(6103,""),
		(6104,""),
		(6105,""),
		(6106,""),
		(6107,""),
		(6108,""),
		(6109,""),
		(6110,"Item cut from the horns of the Regal Ancestor Spirit.<<NEWLINE>><<NEWLINE>>Restore FP upon defeating enemies.<<NEWLINE>><<NEWLINE>>A number of new growths bud from the antler-like horns of the fallen king, each glowing with light. Thus does new life grow from death, and from death, one obtains power."),
])});
