use std::{collections::HashMap, sync::LazyLock};

pub static ACCESSORY_CAPTION_DLC01: LazyLock<HashMap<u32, &'static str>> = LazyLock::new(|| {
    HashMap::from([
		(2220,"A talisman depicting a set of perfume bottles.<<NEWLINE>>Raises potency of arts employing perfume.<<NEWLINE>><<NEWLINE>>There are gardens known only to the perfumers. Whether hidden on the fringes of the highlands, or obscured by shadows inside caves, the flowers blossom in secret, waiting to impart their scent."),
		(7000,"A medallion with crimson amber inlaid.<<NEWLINE>>Boosts maximum HP by the utmost.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>These medallions, of the largest variety, were conferred to Godwyn's inner circle of distinguished golden knights."),
		(7001,""),
		(7002,""),
		(7003,""),
		(7004,""),
		(7005,""),
		(7006,""),
		(7007,""),
		(7008,""),
		(7009,""),
		(7010,"A medallion with cerulean amber inlaid.<<NEWLINE>>Boosts maximum FP by the utmost.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>These medallions, of the largest variety, were conferred to Godwyn's inner circle of distinguished golden knights."),
		(7011,""),
		(7012,""),
		(7013,""),
		(7014,""),
		(7015,""),
		(7016,""),
		(7017,""),
		(7018,""),
		(7019,""),
		(7020,"A medallion with viridian amber inlaid.<<NEWLINE>>Boosts maximum stamina by the utmost.<<NEWLINE>><<NEWLINE>>The Erdtree's old sap becomes amber, treasured as the most precious of jewels in the age of Godfrey, the first Elden Lord.<<NEWLINE>><<NEWLINE>>These medallions, of the largest variety, were conferred to Godwyn's inner circle of distinguished golden knights."),
		(7021,""),
		(7022,""),
		(7023,""),
		(7024,""),
		(7025,""),
		(7026,""),
		(7027,""),
		(7028,""),
		(7029,""),
		(7030,"A talisman in the shape of a two-headed green turtle.<<NEWLINE>>Greatly raises stamina recovery speed.<<NEWLINE>><<NEWLINE>>Turtles are known as a nutritious ingredient, symbolic of inexhaustible power.<<NEWLINE>><<NEWLINE>>Two-headed turtles are a favorite subject in the land of the tower, due to the spiral shape of their intertwined necks."),
		(7031,""),
		(7032,""),
		(7033,""),
		(7034,""),
		(7035,""),
		(7036,""),
		(7037,""),
		(7038,""),
		(7039,""),
		(7040,"Ceremonial accoutrement worn by hornsent.<<NEWLINE>>Vastly raises robustness.<<NEWLINE>>(Robustness governs resistance to blood loss and frost.)<<NEWLINE>><<NEWLINE>>Horns are sublime artifacts to hornsent, and their presence confirms the belief that they are a chosen people.<<NEWLINE>><<NEWLINE>>Only the repeated sprouting of fresh horns can create a tangled horn, which is viewed as an irrefutable symbol of primacy."),
		(7041,""),
		(7042,""),
		(7043,""),
		(7044,""),
		(7045,""),
		(7046,""),
		(7047,""),
		(7048,""),
		(7049,""),
		(7050,"Ceremonial accoutrement worn by hornsent.<<NEWLINE>>Vastly raises immunity.<<NEWLINE>>(Immunity governs resistance to poison and rot.)<<NEWLINE>><<NEWLINE>>Horns are sublime artifacts to hornsent, and their presence confirms the belief that they are a chosen people.<<NEWLINE>><<NEWLINE>>Only the repeated sprouting of fresh horns can create a tangled horn, which is viewed as an irrefutable symbol of primacy."),
		(7051,""),
		(7052,""),
		(7053,""),
		(7054,""),
		(7055,""),
		(7056,""),
		(7057,""),
		(7058,""),
		(7059,""),
		(7060,"Ceremonial accoutrement worn by hornsent.<<NEWLINE>>Vastly raises focus.<<NEWLINE>>(Focus governs resistance to sleep and madness.)<<NEWLINE>><<NEWLINE>>Horns are sublime artifacts to hornsent, and their presence confirms the belief that they are a chosen people.<<NEWLINE>><<NEWLINE>>Only the repeated sprouting of fresh horns can create a tangled horn, which is viewed as an irrefutable symbol of primacy."),
		(7080,"Vividly-colored ceremonial accoutrement worn by hornsent.<<NEWLINE>><<NEWLINE>>Vastly raises immunity, robustness, and focus.<<NEWLINE>><<NEWLINE>>Horns are sublime artifacts to hornsent, and their presence confirms the belief that they are a chosen people.<<NEWLINE>><<NEWLINE>>Only the repeated sprouting of fresh horns can create a tangled horn, which is viewed as an irrefutable symbol of primacy."),
		(7081,""),
		(7082,""),
		(7083,""),
		(7084,""),
		(7085,""),
		(7086,""),
		(7087,""),
		(7088,""),
		(7089,""),
		(7090,"Talisman with a large depiction of a blue ancient dragon.<<NEWLINE>>Boosts magic damage negation by the utmost.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(7091,""),
		(7092,""),
		(7093,""),
		(7094,""),
		(7095,""),
		(7096,""),
		(7097,""),
		(7098,""),
		(7099,""),
		(7100,"Talisman with a large depiction of a red ancient dragon.<<NEWLINE>>Boosts fire damage negation by the utmost.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(7101,""),
		(7102,""),
		(7103,""),
		(7104,""),
		(7105,""),
		(7106,""),
		(7107,""),
		(7108,""),
		(7109,""),
		(7110,"Talisman with a large depiction of a yellow ancient dragon.<<NEWLINE>>Boosts lightning damage negation by the utmost.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(7111,""),
		(7112,""),
		(7113,""),
		(7114,""),
		(7115,""),
		(7116,""),
		(7117,""),
		(7118,""),
		(7119,""),
		(7120,"A braid of golden hair, cut loose.<<NEWLINE>>Queen Marika's offering to the Grandmother.<<NEWLINE>><<NEWLINE>>Boosts holy damage negation by the utmost.<<NEWLINE>><<NEWLINE>>What was her prayer? Her wish, her confession?<<NEWLINE>>There is no one left to answer, and Marika never returned home again."),
		(7121,""),
		(7122,""),
		(7123,""),
		(7124,""),
		(7125,""),
		(7126,""),
		(7127,""),
		(7128,""),
		(7129,""),
		(7130,"Talisman with a large depiction of a pearlescent ancient dragon.<<NEWLINE>>Boosts non-physical damage negation by the utmost.<<NEWLINE>><<NEWLINE>>The ancient dragons, who ruled in the prehistoric era before the Erdtree, would protect their lord as a wall of living rock.<<NEWLINE>>And so it is that the shape of the dragon has become symbolic of all manner of protections."),
		(7131,""),
		(7132,""),
		(7133,""),
		(7134,""),
		(7135,""),
		(7136,""),
		(7137,""),
		(7138,""),
		(7139,""),
		(7140,"A crimson-colored talisman patterned after an Erdtree seed.<<NEWLINE>>Greatly boosts HP restoration from the Flask of Crimson Tears.<<NEWLINE>><<NEWLINE>>The Erdtree seed of this talisman was presumed to be an object of myth. This age-old artifact also depicts the Two Fingers, perhaps harking back to the birth of the Erdtree."),
		(7141,""),
		(7142,""),
		(7143,""),
		(7144,""),
		(7145,""),
		(7146,""),
		(7147,""),
		(7148,""),
		(7149,""),
		(7150,"A cerulean-colored talisman patterned after an Erdtree seed.<<NEWLINE>>Greatly boosts FP restoration from the Flask of Cerulean Tears.<<NEWLINE>><<NEWLINE>>The Erdtree seed of this talisman was presumed to be an object of myth. This age-old artifact also depicts the Two Fingers, perhaps harking back to the birth of the Erdtree."),
		(8000,"Talisman depicting the blessed boon that is a droplet of the blue, luminescent sap of the Erdtree.<<NEWLINE>><<NEWLINE>>Gradually restores FP.<<NEWLINE>><<NEWLINE>>It was once thought that the blessed sap of the Erdtree would drip from its boughs forever—but that age of plenty swiftly came to a close, and with time, the Erdtree became more an object of faith."),
		(8001,""),
		(8002,""),
		(8003,""),
		(8004,""),
		(8005,""),
		(8006,""),
		(8007,""),
		(8008,""),
		(8009,""),
		(8010,"A talisman fashioned from thin feathers that embody the aspects of various creatures.<<NEWLINE>>Said to have grown on the human body long ago.<<NEWLINE>><<NEWLINE>>Improves backsteps but increases damage taken at all times.<<NEWLINE>><<NEWLINE>>Hornsent view the Crucible as sacred for the refinement wrought through its evolutionary gifts. Most prominently, their tangled horns."),
		(8011,""),
		(8012,""),
		(8013,""),
		(8014,""),
		(8015,""),
		(8016,""),
		(8017,""),
		(8018,""),
		(8019,""),
		(8020,"A talisman engraved with the lore of an outer god.<<NEWLINE>>Raises arcane.<<NEWLINE>><<NEWLINE>>The clan, who lost everything in the great fires, peered upon the corpse of their ancestor, normally an act of sanctity, and saw in its shadow a twisted deity.<<NEWLINE>><<NEWLINE>>The clan had suffered such torment that the horrible thing was taken as an object of worship."),
		(8021,""),
		(8022,""),
		(8023,""),
		(8024,""),
		(8025,""),
		(8026,""),
		(8027,""),
		(8028,""),
		(8029,""),
		(8030,"Shattered linchpin stone.<<NEWLINE>><<NEWLINE>>Raises potency of kicking and stomping skills.<<NEWLINE>><<NEWLINE>>Linchpin stones are spiritual anchors said to hold the ground in place and quell the fury of earthquakes—when this one shattered, the surrounding town fell into the broken earth. One account claimed that the moon itself had come tumbling down."),
		(8031,""),
		(8032,""),
		(8033,""),
		(8034,""),
		(8035,""),
		(8036,""),
		(8037,""),
		(8038,""),
		(8039,""),
		(8040,"A talisman depicting a warrior two-handing a sword.<<NEWLINE>>Enhances attacks with two-handed weapons.<<NEWLINE>><<NEWLINE>>The horned warriors were fitting figureheads for the military might of the tower they kept watch over, their deft attacks slashing through any and all foes."),
		(8041,""),
		(8042,""),
		(8043,""),
		(8044,""),
		(8045,""),
		(8046,""),
		(8047,""),
		(8048,""),
		(8049,""),
		(8050,"A talisman depicting a raised spear on a backdrop of flames, in remembrance of the lives lost in the sacred crusade led by Messmer.<<NEWLINE>><<NEWLINE>>Raises attack power after defeating an enemy.<<NEWLINE>><<NEWLINE>>The warriors who fought in the crusade set aside both honor and mercy to wantonly impale and scorch those deemed impure.<<NEWLINE>><<NEWLINE>>Those who felt invigorated by each cry of death were the same men who were certain of the sanctity of the campaign."),
		(8051,""),
		(8052,""),
		(8053,""),
		(8054,""),
		(8055,""),
		(8056,""),
		(8057,""),
		(8058,""),
		(8059,""),
		(8060,"A talisman depicting the exultation of the aging untouchable, whose head resembles a sprig of ripe grapes.<<NEWLINE>><<NEWLINE>>Raises attack power when madness is triggered in the vicinity.<<NEWLINE>><<NEWLINE>>'Gift your madness to our Lord.<<NEWLINE>>Bless our brethren with grapes.<<NEWLINE>>Take care that they fully ripen.'"),
		(8061,""),
		(8062,""),
		(8063,""),
		(8064,""),
		(8065,""),
		(8066,""),
		(8067,""),
		(8068,""),
		(8069,""),
		(8070,"A talisman composed of fletched and iron arrows.<<NEWLINE>><<NEWLINE>>Increases the effective range of bows and raises attack power of arrows and bolts."),
		(8090,"Talisman depicting a knight bearing a pearlescent greatshield.<<NEWLINE>>Boosts all non-physical damage negation while guarding.<<NEWLINE>><<NEWLINE>>The nature and the potential of impurity surpassed the understanding of the knights, and so they were forced to prepare for all threats known or unknown."),
		(8091,""),
		(8092,""),
		(8093,""),
		(8094,""),
		(8095,""),
		(8096,""),
		(8097,""),
		(8098,""),
		(8099,""),
		(8100,"A quaint bouquet of dried flowers, offered to a small grave.<<NEWLINE>><<NEWLINE>>Raises attack power when a spirit you have summoned dies.<<NEWLINE>><<NEWLINE>>The sorrow that flows from the untimely demise of a loved one is a tenderness shared by all, regardless of birthplace."),
		(8101,""),
		(8102,""),
		(8103,""),
		(8104,""),
		(8105,""),
		(8106,""),
		(8107,""),
		(8108,""),
		(8109,""),
		(8110,"A talisman depicting an ancient smithing hammer.<<NEWLINE>>Inscribed with a smithscript.<<NEWLINE>><<NEWLINE>>Enhances weapon-throwing attacks.<<NEWLINE>><<NEWLINE>>In ancient times, smithing was a divine act, and blacksmiths interpreted the script they perceived in the wrinkles of molten steel to imbue weapons with souls."),
		(8111,""),
		(8112,""),
		(8113,""),
		(8114,""),
		(8115,""),
		(8116,""),
		(8117,""),
		(8118,""),
		(8119,""),
		(8120,"A talisman depicting a soul taken by sickness.<<NEWLINE>><<NEWLINE>>When certain ailments are triggered, this talisman grants resistance to the same ailment.<<NEWLINE>><<NEWLINE>>When the weak were infected with the dreaded fly sickness, they perished well before the metamorphosis could take hold. Oddly, those who cared for the infected and made certain they were given a proper burial were never afflicted themselves."),
		(8121,""),
		(8122,""),
		(8123,""),
		(8124,""),
		(8125,""),
		(8126,""),
		(8127,""),
		(8128,""),
		(8129,""),
		(8130,"Handicraft depicting a golden crossed-tree.<<NEWLINE>>One of the items conferred to the Needle Knights.<<NEWLINE>><<NEWLINE>>Enhances attacks executed after rolling or backstepping.<<NEWLINE>><<NEWLINE>>Long ago, the Needle Knights were in service of Miquella, but now they are no more. Save for one."),
		(8131,""),
		(8132,""),
		(8133,""),
		(8134,""),
		(8135,""),
		(8136,""),
		(8137,""),
		(8138,""),
		(8139,""),
		(8140,"Handicraft depicting a golden crossed-tree.<<NEWLINE>>One of the items conferred to the Needle Knights.<<NEWLINE>><<NEWLINE>>Enhances dash attacks.<<NEWLINE>><<NEWLINE>>Long ago, the Needle Knights were in service of Miquella, but now they are no more. Save for one."),
		(8141,""),
		(8142,""),
		(8143,""),
		(8144,""),
		(8145,""),
		(8146,""),
		(8147,""),
		(8148,""),
		(8149,""),
		(8150,"A talisman depicting an archer wielding a longbow.<<NEWLINE>>Boosts attack power of precision-aimed shots.<<NEWLINE>><<NEWLINE>>The Albinauric archers were in a class of their own, and their deadly long-range specialists struck fear into the hearts of men."),
		(8151,""),
		(8152,""),
		(8153,""),
		(8154,""),
		(8155,""),
		(8156,""),
		(8157,""),
		(8158,""),
		(8159,""),
		(8160,"A talisman depicting a smiling St. Trina,<<NEWLINE>>a vision conjured deep within a certain man's heart.<<NEWLINE>><<NEWLINE>>Raises attack power when sleep is triggered in the vicinity.<<NEWLINE>><<NEWLINE>>'Only I am allowed to know. Of your velvety sleep. Its sweetly gentle embrace. So please, smile—for me, and only me.'"),
		(8161,""),
		(8162,""),
		(8163,""),
		(8164,""),
		(8165,""),
		(8166,""),
		(8167,""),
		(8168,""),
		(8169,""),
		(8170,"Talisman depicting the dread dragon of the jagged peak, whose roars cause the peak's molten fury to boil and churn.<<NEWLINE>><<NEWLINE>>Raises potency of magma.<<NEWLINE>><<NEWLINE>>Bayle was the foul dragon's name—a terrible harbinger of destruction whose challenge to the ancient Dragonlord ended in grievous mutual injury."),
		(8171,""),
		(8172,""),
		(8173,""),
		(8174,""),
		(8175,""),
		(8176,""),
		(8177,""),
		(8178,""),
		(8179,""),
		(8180,"A charm depicting the crazed, cavorting dance of the divine beast conducted at the tower festival.<<NEWLINE>><<NEWLINE>>Raises potency of storms.<<NEWLINE>><<NEWLINE>>Divine beasts are messengers of the heavens, and their rage mirrors the tumult of the skies, of which storms are the pinnacle."),
		(8181,""),
		(8182,""),
		(8183,""),
		(8184,""),
		(8185,""),
		(8186,""),
		(8187,""),
		(8188,""),
		(8189,""),
		(8190,"A talisman depicting a wizened hand gently gripping a glintstone.<<NEWLINE>><<NEWLINE>>Shortens casting speed for sorcery and incantations by the utmost, but increases damage taken.<<NEWLINE>><<NEWLINE>>Count Ymir was known for his recitations.<<NEWLINE>>'One need only envision the romance of the stars above with adoration for stardust in one's heart to become a great sorcerer. Do so, and you will know love.'"),
		(8191,""),
		(8192,""),
		(8193,""),
		(8194,""),
		(8195,""),
		(8196,""),
		(8197,""),
		(8198,""),
		(8199,""),
		(8200,"A talisman depicting Godfrey, first Elden lord, receiving the precious sap.<<NEWLINE>><<NEWLINE>>Increases poise after using a flask of tears.<<NEWLINE>><<NEWLINE>>The Lord accepted the sap stoically, without any sign of wavering. No wonder Lord of the Erdtree casts a long shadow over the lands."),
		(8201,""),
		(8202,""),
		(8203,""),
		(8204,""),
		(8205,""),
		(8206,""),
		(8207,""),
		(8208,""),
		(8209,""),
		(8210,"A discus made of verdigris, the corroded metal known for its heft.<<NEWLINE>><<NEWLINE>>Raises defense with higher equipment load.<<NEWLINE>><<NEWLINE>>Great weight makes for great strength. The strength to protect others."),
		(8211,""),
		(8212,""),
		(8213,""),
		(8214,""),
		(8215,""),
		(8216,""),
		(8217,""),
		(8218,""),
		(8219,""),
		(8220,"Talisman featuring a gallant portrait of Rellana, the Twin Moon Knight.<<NEWLINE>><<NEWLINE>>Enhances attacks executed after maintaining the same stance for a certain length of time.<<NEWLINE>><<NEWLINE>>Engraved as a reminder of the unparalleled devotion of those who left their homelands to serve Rellana.<<NEWLINE>><<NEWLINE>>'By your leave, we will accompany you wherever your lunar vessel takes you.'"),
		(8221,""),
		(8222,""),
		(8223,""),
		(8224,""),
		(8225,""),
		(8226,""),
		(8227,""),
		(8228,""),
		(8229,""),
		(8230,"A thin, blood-stained dagger. No longer fit for use.<<NEWLINE>><<NEWLINE>>Raises attack power after each critical hit.<<NEWLINE>><<NEWLINE>>Hornsent employed this to honorably end the suffering of a compatriot. After claiming numerous lives, the dagger is now broken, but has acquired a spectral aura."),
		(8231,""),
		(8232,""),
		(8233,""),
		(8234,""),
		(8235,""),
		(8236,""),
		(8237,""),
		(8238,""),
		(8239,""),
		(8240,"A giant mass of intermingling Crucible attributes.<<NEWLINE>><<NEWLINE>>Reduces damage taken from critical hits and head shots and improves the effectiveness of rolling and backstepping, but also increases damage taken at all times.<<NEWLINE>><<NEWLINE>>Rumored to have sprouted upon giants and is known as the 'mother of Crucibles' in ancient tower lore."),
])
});
