use std::{collections::HashMap, sync::LazyLock};

pub static ARTS_CAPTION: LazyLock<HashMap<u32, &'static str>> = LazyLock::new(|| {
    HashMap::from([
		(1,"-"),
		(2,""),
		(3,""),
		(4,""),
		(5,""),
		(6,""),
		(7,""),
		(8,""),
		(9,""),
		(10,"No skill.<<NEWLINE>><<NEWLINE>>This armament has no skill.<<NEWLINE>>If the armament in the other hand has a skill, that skill will be used instead."),
		(100,"Skill: Lion's Claw<<NEWLINE>><<NEWLINE>>Skill of the Redmanes, who fought alongside General Radahn.<<NEWLINE>>Somersault forwards, striking foes with armament."),
		(101,"Skill: Impaling Thrust<<NEWLINE>><<NEWLINE>>Skill that lets piercing armaments overcome enemy shields. Build power, then lunge forward for a strong thrust that pierces an enemy's guard."),
		(102,"Skill: Piercing Fang<<NEWLINE>><<NEWLINE>>Skill used by Yura, the Bloody Finger Hunter.<<NEWLINE>>Starting with the blade held horizontally, make a powerful thrust that cannot be blocked."),
		(103,"Skill: Spinning Slash<<NEWLINE>><<NEWLINE>>Skill favored by dexterous warriors.<<NEWLINE>>Slash foes as your body spins. Additional input allows for a follow-up attack."),
		(104,"Skill: Spinning Reaper<<NEWLINE>><<NEWLINE>>Skill developed to face crowds of enemies.<<NEWLINE>>Slice at foes while performing a great<<NEWLINE>>rotation with the body. The momentum<<NEWLINE>>generated can empower a final, heavy strike."),
		(105,"Skill: Charge Forth<<NEWLINE>><<NEWLINE>>Quickly charge forward with the armament at the hip, carrying the momentum into a thrust.<<NEWLINE>>Hold to cover a greater distance."),
		(106,"Skill: Stamp (Upward Cut)<<NEWLINE>><<NEWLINE>>Brace armament and step into a low stance that prevents recoil from most enemy attacks.<<NEWLINE>>Follow up with a strong attack for an upward strike."),
		(107,"Skill: Stamp (Sweep)<<NEWLINE>><<NEWLINE>>Brace armament and step into a low stance that prevents recoil from most enemy attacks.<<NEWLINE>>Follow up with a strong attack for a sweeping strike."),
		(108,"Skill: Blood Tax<<NEWLINE>><<NEWLINE>>Blood Oath skill granted by the Lord of Blood.<<NEWLINE>>Twist to build power, then unleash a flurry of thrusts that rob the target of both their blood and their HP."),
		(109,"Skill: Repeating Thrust<<NEWLINE>><<NEWLINE>>Twist to build power, then unleash a flurry of thrusts."),
		(110,"Skill: Wild Strikes<<NEWLINE>><<NEWLINE>>Swing armament with wild abandon.<<NEWLINE>>Hold to continue swinging. Can be followed up with a normal or strong attack."),
		(111,"Skill: Spinning Strikes<<NEWLINE>><<NEWLINE>>Polearm skill that performs continuous spinning attacks. Hold to continue the attack. Can be followed up with a normal or strong attack. Nullifies projectiles such as arrows while spinning."),
		(112,"Skill: Double Slash<<NEWLINE>><<NEWLINE>>Skill of superior swordsmen.<<NEWLINE>>Perform a crossing slash attack from a low stance.<<NEWLINE>>Repeated inputs allow for up to two follow-up attacks."),
		(113,"Skill: Prelate's Charge<<NEWLINE>><<NEWLINE>>Slam armament into the ground to create a surge of flames, then charge in.<<NEWLINE>>Hold to continue the charge."),
		(114,"Skill: Unsheathe<<NEWLINE>><<NEWLINE>>Skill of swordsmen from the Land of Reeds.<<NEWLINE>>Sheathe blade, holding it at the hip in a composed stance.<<NEWLINE>>Follow up with a normal or strong attack to perform a swift slash attack."),
		(115,"Skill: Square Off<<NEWLINE>><<NEWLINE>>This skill starts with the sword held level.<<NEWLINE>>Follow up with a normal attack to slash upwards through enemy's guard, or a strong attack to perform a running thrust."),
		(116,"Skill: Giant Hunt<<NEWLINE>><<NEWLINE>>Skill developed for confronting gigantic foes.<<NEWLINE>>Step forward from a low stance, carrying the momentum into a sudden upward thrust."),
		(117,"Skill: Torch Attack<<NEWLINE>><<NEWLINE>>Thrust torch forward to set foes ablaze.<<NEWLINE>>This skill is especially effective against foes who are weak to fire."),
		(118,"Skill: Loretta's Slash<<NEWLINE>><<NEWLINE>>Skill of Loretta the Royal Knight.<<NEWLINE>>Leap forward, imbuing the blade with glintstone, then descend, accelerating into a sweeping slash."),
		(119,"Skill: Poison Moth Flight<<NEWLINE>><<NEWLINE>>Slash with a poison-infused blade.<<NEWLINE>>If the follow-up strike lands on a poisoned foe, it will deal significant damage."),
		(120,"Skill: Spinning Weapon<<NEWLINE>><<NEWLINE>>Defensive skill employed by Carian princesses.<<NEWLINE>>Lifts armament into mid-air, then makes it spin violently. Those it touches will suffer successive attacks."),
		(121,""),
		(122,"Skill: Storm Assault<<NEWLINE>><<NEWLINE>>One of the skills that channel the tempests of Stormveil.<<NEWLINE>>Leap forward through surrounding storm winds and thrust armament downward. The attack will produce more storm winds at the point of impact."),
		(123,"Skill: Stormcaller<<NEWLINE>><<NEWLINE>>One of the skills that channel the tempests of Stormveil. Spin armament to create surrounding storm winds. Repeated inputs allow for up to two follow-up attacks."),
		(124,"Skill: Sword Dance<<NEWLINE>><<NEWLINE>>Quickly close in to perform a series of spinning upward slashes.<<NEWLINE>>Follow up with an additional input to finish with a downward slash."),
		(125,"Skill: Spinning Chain<<NEWLINE>><<NEWLINE>>Spins the striking part of a flail at high speed to attack.<<NEWLINE>>Follow up with a normal or strong attack to link the momentum of this skill into a successive attack."),
		(200,"Skill: Glintblade Phalanx<<NEWLINE>><<NEWLINE>>Skill used by the enchanted knights who served the Carian royal family. Form an arch of magic glintblades overhead, which will attack foes automatically. Follow up with a strong attack to chain this skill into a lunging thrust."),
		(201,"Skill: Sacred Blade<<NEWLINE>><<NEWLINE>>Grants armament's attacks holy essence and fires off a golden blade projectile.<<NEWLINE>>The armament retains its holy essence for a while."),
		(202,"Skill: Ice Spear<<NEWLINE>><<NEWLINE>>Skill of the warriors who served Lunar Princess Ranni.<<NEWLINE>>Spin armament to release cold magic, then channel it into a piercing spear of ice."),
		(203,"Skill: Glintstone Pebble<<NEWLINE>><<NEWLINE>>Skill that employs the glintstone sorcery of the same name.<<NEWLINE>>Follow up with a strong attack to chain this skill into a lunging thrust, performed while the armament is still imbued with glintstone."),
		(204,"Skill: Bloody Slash<<NEWLINE>><<NEWLINE>>Blood Oath skill granted by the Lord of Blood.<<NEWLINE>>From a low stance, coat the blade in your own blood to unleash a rending blood slash in a wide arc."),
		(205,"Skill: Lifesteal Fist<<NEWLINE>><<NEWLINE>>Skill that demonstrates mastery of the art of controlling vital energies.<<NEWLINE>>A slow, controlled punch with an energy-infused fist that renders foes unconscious and steals their HP. Only effective against foes of human build."),
		(206,""),
		(207,"Skill: Eruption<<NEWLINE>><<NEWLINE>>Skill of the knights who serve at Volcano Manor.<<NEWLINE>>Slam armament into the ground, spawning roiling lava which spouts up upon release."),
		(208,"Skill: Prayerful Strike<<NEWLINE>><<NEWLINE>>Raise armament aloft in prayer, then slam it into the ground.<<NEWLINE>>This inspired blow restores HP to the self and nearby allies if it successfully hits."),
		(209,"Skill: Gravitas<<NEWLINE>><<NEWLINE>>Skill originating from the Alabaster Lords, who had skin of stone.<<NEWLINE>>Thrust the armament into the ground to create a gravity well.<<NEWLINE>>In addition to dealing damage, this attack pulls enemies in."),
		(210,"Skill: Storm Blade<<NEWLINE>><<NEWLINE>>Lost skill of Stormveil.<<NEWLINE>>Surround armament with shearing storm winds that can be fired forward.<<NEWLINE>>Can be fired in rapid succession."),
		(211,""),
		(212,"Skill: Earthshaker<<NEWLINE>><<NEWLINE>>Thrust armament into the ground, then gather strength to unleash an earth-shaking shockwave.<<NEWLINE>>Follow up with a strong attack to swing the armament in a sweeping strike."),
		(213,"Skill: Golden Land<<NEWLINE>><<NEWLINE>>Thrust armament into the ground, then gather strength to unleash a blast of sacred energy that coalesces into golden darts. Follow up with a strong attack to swing the armament in a sweeping strike."),
		(214,"Skill: Flaming Strike<<NEWLINE>><<NEWLINE>>Skill that emits flame in a wide frontward arc.<<NEWLINE>>Follow up with a strong attack to perform a lunging, sweeping strike.<<NEWLINE>>This will also coat the armament in fire."),
		(215,""),
		(216,"Skill: Thunderbolt<<NEWLINE>><<NEWLINE>>Skill used by the capital's ancient dragon cult.<<NEWLINE>>Raise armament aloft to call down a bolt of lightning.<<NEWLINE>>Can be fired in rapid succession."),
		(217,"Skill: Lightning Slash<<NEWLINE>><<NEWLINE>>Call down a bolt of lightning into armament, then swing it down to create an explosive shock.<<NEWLINE>>The armament retains the lightning enchantment for a while."),
		(218,"Skill: Carian Grandeur<<NEWLINE>><<NEWLINE>>Carian royal prestige embodied in a skill.<<NEWLINE>>Transform blade into a magical greatsword and swing it down.<<NEWLINE>>Can be charged to increase its power by up to two levels."),
		(219,"Skill: Carian Greatsword<<NEWLINE>><<NEWLINE>>Carian royal prestige embodied in a skill.<<NEWLINE>>Transform blade into a magical greatsword and swing it down.<<NEWLINE>>Can be charged to increase its power."),
		(220,"Skill: Vacuum Slice<<NEWLINE>><<NEWLINE>>Lost skill of ancient heroes.<<NEWLINE>>Hold the armament aloft to surround it with a shearing vacuum, then launch it forwards as a blade-like projectile."),
		(221,"Skill: Black Flame Tornado<<NEWLINE>><<NEWLINE>>Spin armament overhead and then plunge it into the ground to summon a raging vortex of black flames.<<NEWLINE>>Hold to create an initial flame tornado while spinning the armament."),
		(222,"Skill: Sacred Ring of Light<<NEWLINE>><<NEWLINE>>Skill used by the commanders of the Cleanrot Knights. Gather a sacred ring of light in the armament, then fire it forwards.<<NEWLINE>>Can be fired in rapid succession."),
		(223,"Skill: Firebreather<<NEWLINE>><<NEWLINE>>Blow into torch flame, spreading flames in a wide frontward arc. The flames on the ground will continue to burn for a short time."),
		(224,"Skill: Blood Blade<<NEWLINE>><<NEWLINE>>Wound self to coat the armament with blood, then unleash an airborne blood blade that causes hemorrhaging.<<NEWLINE>>Can be fired in rapid succession."),
		(225,"Skill: Phantom Slash<<NEWLINE>><<NEWLINE>>Skill inspired by the fond remembrances of the Night's Cavalry. Creates an apparition of the knights' former instructor who guides a joint lunging upward swing. Additional input allows for a follow-up attack."),
		(226,"Skill: Spectral Lance<<NEWLINE>><<NEWLINE>>Skill of the headless Mausoleum Knights.<<NEWLINE>>Hurl a phantasmic spear at foes."),
		(227,"Skill: Chilling Mist<<NEWLINE>><<NEWLINE>>Coat armament in frost, and then slash, spreading frigid mist forwards.<<NEWLINE>>The armament retains its frost for a while."),
		(228,"Skill: Poisonous Mist<<NEWLINE>><<NEWLINE>>Bathe armament in poison, and then slash, spreading toxic mist forwards.<<NEWLINE>>The armament retains its poison for a while."),
		(300,"Skill: Shield Bash<<NEWLINE>><<NEWLINE>>Brace behind shield before using bodyweight to ram foes while maintaining guarding stance.<<NEWLINE>>Weaker enemies will be shoved backwards, and can even be staggered."),
		(301,"Skill: Barricade Shield<<NEWLINE>><<NEWLINE>>Skill made famous by Sir Neidhardt.<<NEWLINE>>Focus your energy into the shield, temporarily hardening it to deflect greater blows."),
		(302,"Skill: Parry<<NEWLINE>><<NEWLINE>>Use this skill in time with a foe's melee attack to deflect it and break that foe's stance.<<NEWLINE>>This provides an opening to perform a critical hit."),
		(303,"Skill: Buckler Parry<<NEWLINE>><<NEWLINE>>Use this skill in time with a foe's melee attack to deflect it and break that foe's stance.<<NEWLINE>>This is faster than a regular parry."),
		(304,"Skill: Parry<<NEWLINE>><<NEWLINE>>Use this skill in time with a foe's melee attack to deflect it and break that foe's stance.<<NEWLINE>>This provides an opening to perform a critical hit."),
		(305,"Skill: Carian Retaliation<<NEWLINE>><<NEWLINE>>Swing the shield to dispel incoming sorceries and incantations, transforming the magic into retaliatory glintblades.<<NEWLINE>>Can also be used in the same way as a regular parry."),
		(306,"Skill: Storm Wall<<NEWLINE>><<NEWLINE>>Swing the shield to create a wall of storm winds in front of you, deflecting arrows and other such physical projectiles.<<NEWLINE>>Can also be used in the same way as a regular parry."),
		(307,"Skill: Golden Parry<<NEWLINE>><<NEWLINE>>Perform an Erdtree incantation and swing the shield to deflect enemy attacks and break their stance.<<NEWLINE>>Effective even at a slight distance."),
		(308,"Skill: Shield Crash<<NEWLINE>><<NEWLINE>>Two-hand the shield and charge forwards while maintaining guard. Weaker enemies will be shoved backwards and can even be staggered.<<NEWLINE>>Hold to extend the duration of the charge forwards."),
		(309,"Skill: Thops's Barrier<<NEWLINE>><<NEWLINE>>Erect a magical forcefield while swinging the shield to deflect sorceries and incantations.<<NEWLINE>>Can also be used in the same way as a regular parry."),
		(400,"Skill: Through and Through<<NEWLINE>><<NEWLINE>>Powerful archery skill using a greatbow held in an oblique stance.<<NEWLINE>>Ready the greatbow, then twist the bowstring to fire a mighty greatarrow that can penetrate through enemies."),
		(401,"Skill: Barrage<<NEWLINE>><<NEWLINE>>Archery skill using a bow held horizontally.<<NEWLINE>>Ready the bow, then fire off a rapid succession of shots faster than the eye can see."),
		(402,"Skill: Mighty Shot<<NEWLINE>><<NEWLINE>>Archery skill performed from an oblique stance.<<NEWLINE>>Ready the bow, then pull the bowstring to its limit to enhance the power of the shot, penetrating the enemy's guard."),
		(403,""),
		(404,"Skill: Enchanted Shot<<NEWLINE>><<NEWLINE>>Archery skill that enlivens the arrow with spiritual essence.<<NEWLINE>>The resulting shot will fly faster than regular shots and change its trajectory to follow the target."),
		(405,"Skill: Sky Shot<<NEWLINE>><<NEWLINE>>Archery skill performed from a low stance.<<NEWLINE>>Ready the bow, then fire an arrow high up into the air, arcing so as to strike the enemy from above when it comes down."),
		(406,"Skill: Rain of Arrows<<NEWLINE>><<NEWLINE>>Archery skill performed from a low stance.<<NEWLINE>>Ready the bow, then fire a burst of arrows into the sky to shower the enemy with projectiles."),
		(407,"Skill: Invisible Arrow<<NEWLINE>><<NEWLINE>>Nearly invisible magic arrow that leaves<<NEWLINE>>no trail and disappears on impact."),
		(501,"Skill: Hoarfrost Stomp<<NEWLINE>><<NEWLINE>>Stomp hard to spread a trail of freezing mist on the ground.<<NEWLINE>>The mist applies the frost status effect."),
		(502,"Skill: Storm Stomp<<NEWLINE>><<NEWLINE>>One of the skills that channel the tempests of Stormveil.<<NEWLINE>>Stomp hard on the ground to kick up a momentary storm."),
		(503,"Skill: Kick<<NEWLINE>><<NEWLINE>>Push an enemy back with a high kick.<<NEWLINE>>Effective against enemies who are guarding, and can break a foe's stance.<<NEWLINE>>Sometimes a simple tool is the most effective."),
		(504,"Skill: Lightning Ram<<NEWLINE>><<NEWLINE>>Skill inspired by tumbling rams.<<NEWLINE>>Let out a bleat, then tumble forwards, clad in lightning.<<NEWLINE>>Tumbles can be repeated in rapid succession."),
		(505,"Skill: Flame of the Redmanes<<NEWLINE>><<NEWLINE>>Skill of the Redmanes, who fought alongside General Radahn.<<NEWLINE>>Produce a powerful burst of flames in a wide frontward arc."),
		(506,"Skill: Ground Slam<<NEWLINE>><<NEWLINE>>Jump up high into the air and crash down on the ground ahead.<<NEWLINE>>The resulting pratfall sends a powerful shockwave in all directions."),
		(507,"Skill: Golden Slam<<NEWLINE>><<NEWLINE>>Skill of the avatars who protect Minor Erdtrees.<<NEWLINE>>Jump up high into the air and crash down on the ground ahead.<<NEWLINE>>The resulting pratfall sends golden shockwaves in all directions."),
		(508,"Skill: Waves of Darkness<<NEWLINE>><<NEWLINE>>Plunge armament into the ground to release three waves of darkness.<<NEWLINE>>Follow up with a strong attack to swing the armament in a sweeping strike."),
		(509,"Skill: Hoarah Loux's Earthshaker<<NEWLINE>><<NEWLINE>>Slam both hands onto the ground to violently shake the earth and unleash a shockwave.<<NEWLINE>>Follow up with an additional input to slam the ground again."),
		(600,"Skill: Determination<<NEWLINE>><<NEWLINE>>A knightly skill.<<NEWLINE>>Hold the flat of the armament to your face and pledge your resolve, powering up your next attack."),
		(601,"Skill: Royal Knight's Resolve<<NEWLINE>><<NEWLINE>>Skill of the knights who once served the Elden Lord.<<NEWLINE>>Hold the flat of the armament to your face and pledge your resolve, greatly powering up your next attack."),
		(602,"Skill: Assassin's Gambit<<NEWLINE>><<NEWLINE>>Skill that masks the user's presence at the cost of a self-inflicted wound.<<NEWLINE>>Grants near-invisibility and silences footsteps."),
		(603,"Skill: Golden Vow<<NEWLINE>><<NEWLINE>>Skill passed down from antiquity among the knights of the capital. Raise armament aloft and pledge to honor the Erdtree in battle, granting self and nearby allies increased attack power and defense."),
		(604,"Skill: Sacred Order<<NEWLINE>><<NEWLINE>>Skill of the Golden Order fundamentalist knights.<<NEWLINE>>Perform a salute and grant the armament holy essence.<<NEWLINE>>Highly effective against Those Who Live in Death."),
		(605,"Skill: Shared Order<<NEWLINE>><<NEWLINE>>Skill of the Golden Order fundamentalist knights.<<NEWLINE>>Grant the armament and those of nearby allies holy essence.<<NEWLINE>>Highly effective against Those Who Live in Death."),
		(606,"Skill: Seppuku<<NEWLINE>><<NEWLINE>>A forbidden technique used by swordsmen from the Land of Reeds. Plunge the blade into your stomach to stain it with blood. Increases attack power and improves ability to inflict blood loss."),
		(607,"Skill: Cragblade<<NEWLINE>><<NEWLINE>>Skill that manipulates gravity.<<NEWLINE>>Bury the armament in the ground, pulling rocks from the earth to reinforce it. Increases attack power and makes it easier to break enemy stance."),
		(650,"Skill: Barbaric Roar<<NEWLINE>><<NEWLINE>>Let loose a bestial roar to rally the spirit and increase attack power.<<NEWLINE>>While active, strong attacks change to savage combo attacks."),
		(651,"Skill: War Cry<<NEWLINE>><<NEWLINE>>Give a war cry to rally the spirit and increase attack power.<<NEWLINE>>While active, strong attacks change to charging attacks."),
		(652,"Skill: Beast's Roar<<NEWLINE>><<NEWLINE>>Unleash a beastly roar, rending the air as a forward-travelling projectile."),
		(653,"Skill: Troll's Roar<<NEWLINE>><<NEWLINE>>Look into the distance and let out an intense roar, generating a powerful shockwave that blows back surrounding foes.<<NEWLINE>>Follow up with a strong attack to slam the armament down."),
		(654,"Skill: Braggart's Roar<<NEWLINE>><<NEWLINE>>Declare your presence with a boastful roar.<<NEWLINE>>Raises attack power, defense, and stamina recovery speed."),
		(700,"Skill: Endure<<NEWLINE>><<NEWLINE>>Assume an anchored stance to brace for incoming attacks, briefly boosting poise.<<NEWLINE>>Damage taken while using this skill is reduced."),
		(701,"Skill: Vow of the Indomitable<<NEWLINE>><<NEWLINE>>Skill of the ancient warriors of the Erdtree.<<NEWLINE>>Hold shield aloft to imbue yourself with golden power, granting momentary invincibility."),
		(702,"Skill: Holy Ground<<NEWLINE>><<NEWLINE>>Raise shield to create an Erdtree-consecrated area that continuously restores HP and boosts defense for self and allies inside it."),
		(800,"Skill: Quickstep<<NEWLINE>><<NEWLINE>>Skill prized by the crafty and fleet of foot.<<NEWLINE>>Perform a quickstep maneuver that allows for circling around lock-on targets."),
		(801,"Skill: Bloodhound's Step<<NEWLINE>><<NEWLINE>>Skill that allows the user to become temporarily invisible while dodging at high speed. Moves faster and travels farther than a regular quickstep.<<NEWLINE>>This skill can be used to circle around lock-on targets."),
		(802,"Skill: Raptor of the Mists<<NEWLINE>><<NEWLINE>>Duck into a low stance, momentarily vanishing.<<NEWLINE>>If an enemy attack connects, avian wings will allow for a quick escape into the air."),
		(850,"Skill: White Shadow's Lure<<NEWLINE>><<NEWLINE>>Hold armament in a brief, silent prayer to create a white shadow.<<NEWLINE>>The apparition lures in foes of human build who are not in combat, drawing their aggression. Effective on demi-humans even if they are already in a combat state."),
		(1000,"Unique Skill: Surge of Faith<<NEWLINE>><<NEWLINE>>Set the flames of Birac's faith ablaze in the cranial vessel, then raise it aloft to rain down fireballs in all directions.<<NEWLINE>>Repeated inputs will continue to raise the armament aloft, continuing the attack."),
		(1001,"Unique Skill: Flame Spit<<NEWLINE>><<NEWLINE>>Ready the shield, then launch a fireball from the barrel.<<NEWLINE>>The fireball explodes on impact."),
		(1002,"Unique Skill: Tongues of Fire<<NEWLINE>><<NEWLINE>>Ready the shield, then spray violent jets of fire from the tongues protruding from its maw.<<NEWLINE>>Hold to continue spraying fire. This skill can be used while walking."),
		(1003,"Unique Skill: Oracular Bubble<<NEWLINE>><<NEWLINE>>Blow on the horn to release a magic bubble.<<NEWLINE>>The bubble floats gently through the air towards its target."),
		(1004,"Unique Skill: Bubble Shower<<NEWLINE>><<NEWLINE>>Blow on the horn to release a spume of magic bubbles.<<NEWLINE>>The bubbles float gently before raining down on the target."),
		(1005,"Unique Skill: Great Oracular Bubble<<NEWLINE>><<NEWLINE>>Blow on the horn to release a massive magic bubble.<<NEWLINE>>The bubble floats gently through the air towards its target."),
		(1006,"Unique Skill: Sea of Magma<<NEWLINE>><<NEWLINE>>Swing a molten whip overhead to temporarily cover the surrounding area in a sea of magma.<<NEWLINE>>Hold to continue swinging the lava whip."),
		(1007,"Unique Skill: Viper Bite<<NEWLINE>><<NEWLINE>>Give the shield a quick shake to temporarily bring the bronze viper to life, inciting it to lash out and bite foes."),
		(1008,"Unique Skill: Moonlight Greatsword<<NEWLINE>><<NEWLINE>>Raise the sword aloft, bathing it in the light of the dark moon.<<NEWLINE>>Temporarily increases magic attack power and imbues blade with frost.<<NEWLINE>>Charged attacks release blasts of moonlight."),
		(1009,"Unique Skill: Siluria's Woe<<NEWLINE>><<NEWLINE>>Thrust the weapon in a spiraling motion, surrounding it in a vortex of wind.<<NEWLINE>>Charged attacks have the power to blow away enemies and can fire the tornado forwards."),
		(1010,"Unique Skill: Rallying Standard<<NEWLINE>><<NEWLINE>>Hoist the war banner aloft and give a rallying command.<<NEWLINE>>Raises attack power and defense for self and nearby allies."),
		(1011,"Unique Skill: Bear Witness!<<NEWLINE>><<NEWLINE>>Grant the small dragon a fleeting glimpse of life and thrust it skyward, spewing flames over a wide frontward area."),
		(1012,"Unique Skill: Eochaid's Dancing Blade<<NEWLINE>><<NEWLINE>>Infuse the sword with energy, then fling it forwards in a corkscrew attack. The sword continuously deals damage while violently spinning.<<NEWLINE>>Charge the attack to increase reach and duration of the spin."),
		(1013,"Unique Skill: Soul Stifler<<NEWLINE>><<NEWLINE>>Raise the greathorn's wings to summon a soul-sapping miasma.<<NEWLINE>>Enemies in the affected area will temporarily suffer from reduced defense."),
		(1014,"Unique Skill: Taker's Flames<<NEWLINE>><<NEWLINE>>Raise the sacred sword aloft to set it ablaze with blasphemous flames, then bring it down to fire off a forward blast.<<NEWLINE>>The flames steal HP from those they touch."),
		(1015,"Unique Skill: Shriek of Milos<<NEWLINE>><<NEWLINE>>Lets out a horrific cursed scream that reduces all damage negation and status resistances for nearby foes.<<NEWLINE>>While active, strong attacks will change to a combo attack."),
		(1016,"Unique Skill: Reduvia Blood Blade<<NEWLINE>><<NEWLINE>>Slash with the wicked dagger, transforming its never-drying bloodstains into airborne blades that cause blood loss.<<NEWLINE>>Can be fired in rapid succession."),
		(1017,"Unique Skill: Glintstone Dart<<NEWLINE>><<NEWLINE>>Skill that builds from the Glintstone Pebble sorcery.<<NEWLINE>>Charge the skill to upgrade it to Glintstone Dart.<<NEWLINE>>Follow up with a strong attack to chain this skill into a lunging thrust."),
		(1018,"Unique Skill: Flowing Form<<NEWLINE>><<NEWLINE>>Temporarily transforms armament into its liquid form.<<NEWLINE>>Swing the armament like a whip to perform a sweeping slice over a wide area."),
		(1019,"Unique Skill: Night-and-Flame Stance<<NEWLINE>><<NEWLINE>>Hold the sword level and prepare to cast a sorcery.<<NEWLINE>>Follow up with a normal attack to cast the Night Comet sorcery, or a strong attack to sweep forward with a burst of flames."),
		(1020,"Unique Skill: Wave of Gold<<NEWLINE>><<NEWLINE>>Imbue the sword with bygone golden glory, then fire it at foes.<<NEWLINE>>A wide, golden wave fans out forwards, sweeping through all enemies caught in its path."),
		(1021,"Unique Skill: Ruinous Ghostflame<<NEWLINE>><<NEWLINE>>Swing the sword to bathe its blade in ghostflame.<<NEWLINE>>The ghostflame adds magic damage to attacks, and also has a bitterly cold bite."),
		(1022,"Unique Skill: Establish Order<<NEWLINE>><<NEWLINE>>Raise the armament in a salute, releasing a golden explosion.<<NEWLINE>>Repeated inputs send out waves of golden light."),
		(1023,"Unique Skill: Mists of Slumber<<NEWLINE>><<NEWLINE>>Releases a faint purple mist that spreads across a wide frontwards area.<<NEWLINE>>This mist inflicts the sleep ailment upon foes."),
		(1024,"Unique Skill: Spearcall Ritual<<NEWLINE>><<NEWLINE>>Thrust the spear high, bearing prayers into the sky to summon a downpour of spectral spears."),
		(1025,"Unique Skill: Wolf's Assault<<NEWLINE>><<NEWLINE>>Infuse the greatsword with frost, then perform a forward somersault to plunge it into the ground. Then, pull it out to release a cold blast."),
		(1026,"Unique Skill: Thundercloud Form<<NEWLINE>><<NEWLINE>>Temporarily transform into a red thundercloud and fly through the air, then plunge down with a lightning-infused blade.<<NEWLINE>>Hold to increase the reach of the thundercloud form."),
		(1027,"Unique Skill: Cursed-Blood Slice<<NEWLINE>><<NEWLINE>>Brace, then charge forward to deliver a downward diagonal slice.<<NEWLINE>>The bloody trail of the blade is followed by a burst of flame.<<NEWLINE>>Additional input allows for a follow-up attack."),
		(1028,"Unique Skill: Waterfowl Dance<<NEWLINE>><<NEWLINE>>Perform a series of one-footed leaps in the manner of a waterfowl to unleash a swift yet graceful slashing combo.<<NEWLINE>>Repeated inputs allow for up to two follow-up attacks."),
		(1029,"Unique Skill: Gold Breaker<<NEWLINE>><<NEWLINE>>Leap up high and, while suspended in midair, imbue the rune shard with light before smashing it down hard onto the ground.<<NEWLINE>>The heroic Radagon's signature attack."),
		(1030,"Unique Skill: I Command Thee, Kneel!<<NEWLINE>><<NEWLINE>>Repeatedly smash the Axe of Godrick into the ground, unleashing two earth-shaking shockwaves.<<NEWLINE>>Follow up with an additional input to produce a third shockwave."),
		(1031,"Unique Skill: Regal Roar<<NEWLINE>><<NEWLINE>>Let loose a mighty war cry, raising attack power, while sending out a shockwave that cannot be guarded against by stomping the ground. While active, strong attack becomes a lunging slash."),
		(1032,"Unique Skill: Starcaller Cry<<NEWLINE>><<NEWLINE>>Bring the two swords together and roar into the skies, pulling in enemies with a gravitational wave.<<NEWLINE>>Follow up with an additional input to slam down with gravity-infused swords."),
		(1033,"Unique Skill: Wave of Destruction<<NEWLINE>><<NEWLINE>>Raise the sword up high, then strike it against the ground to fire off a wave of gravitational force."),
		(1034,"Unique Skill: Bloodboon Ritual<<NEWLINE>><<NEWLINE>>Raise the sacred spear and pierce the body of the Formless Mother. Stab up to three times, creating explosions of blood with each thrust.<<NEWLINE>>This skill will coat the armament with bloodflame for a while."),
		(1035,"Unique Skill: Flowing Form<<NEWLINE>><<NEWLINE>>Temporarily transforms armament into its liquid form. Swing the armament like a whip to strike surroundings before slamming its teardrop-shaped head down."),
		(1036,"Unique Skill: Blade of Death<<NEWLINE>><<NEWLINE>>Unleash the power of the Rune of Death to fire off a blade-like projectile.<<NEWLINE>>In addition to dealing immediate damage, the blade reduces the enemy's maximum HP and continues to wear down HP for a while."),
		(1037,"Unique Skill: Blade of Gold<<NEWLINE>><<NEWLINE>>Leap into the air, charging the armament with golden flames that are then shot at the enemy as a single, blade-like projectile.<<NEWLINE>>Inflicts holy damage."),
		(1038,"Unique Skill: Destined Death<<NEWLINE>><<NEWLINE>>Set free the remnants of Destined Death, plunging the greatsword into the ground to summon a myriad of blades. In addition to dealing immediate damage, this attack reduces the enemy's maximum HP and continues to wear down HP for a short time."),
		(1039,"Unique Skill: Spinning Wheel<<NEWLINE>><<NEWLINE>>Strike the wheel against the ground to set it spinning at top speed. Hold to keep the wheel spinning. Can be used while walking to push the armament into enemies."),
		(1040,"Unique Skill: Alabaster Lord's Pull<<NEWLINE>><<NEWLINE>>Thrust the armament into the ground to create a gravity well. In addition to dealing damage, this attack pulls enemies in.<<NEWLINE>>Has a greater area of effect than Gravitas."),
		(1041,"Unique Skill: Onyx Lord's Repulsion<<NEWLINE>><<NEWLINE>>Thrust the armament into the ground to create a gravity well. In addition to dealing damage, this attack sends enemies flying away."),
		(1042,"Unique Skill: Oath of Vengeance<<NEWLINE>><<NEWLINE>>Swear an oath upon the greatsword to avenge the clan, temporarily raising all attributes for a certain duration. While the oath's effects are active, poise will also be increased."),
		(1043,"Unique Skill: Ice Lightning Sword<<NEWLINE>><<NEWLINE>>Call down a bolt of ice lightning into the blade and bring it down upon a foe.<<NEWLINE>>The ice lightning effect will persist for a while."),
		(1044,"Unique Skill: Regal Beastclaw<<NEWLINE>><<NEWLINE>>Slam the hammer into the ground, rending the land asunder with the armament's five bestial claws."),
		(1045,"Unique Skill: Flame Dance<<NEWLINE>><<NEWLINE>>Imbue the red braid with the Giants' Flame and lash out in a wide range with a series of agile swings."),
		(1046,"Unique Skill: Claw Flick<<NEWLINE>><<NEWLINE>>Cause the finger to swell, then flex to build up strength before giving enemies an almighty flick."),
		(1047,"Unique Skill: Nebula<<NEWLINE>><<NEWLINE>>Imbue the Naturalborn's stars with magic to perform a sweeping strike.<<NEWLINE>>This attack leaves a dark cloud of stars in its wake that lingers briefly before exploding."),
		(1048,"Unique Skill: Ghostflame Ignition<<NEWLINE>><<NEWLINE>>Thrust out the barbed rod and set its tip alight with ghostflame.<<NEWLINE>>Follow up with a normal attack to set the ground ablaze with ghostflame, or a strong attack to trigger a massive explosion."),
		(1049,"Unique Skill: Ancient Lightning Spear<<NEWLINE>><<NEWLINE>>Imbue the armament with the ancient dragons' red lightning, then throw it as a spear.<<NEWLINE>>Can be charged to increase its power."),
		(1050,"Unique Skill: Frenzyflame Thrust<<NEWLINE>><<NEWLINE>>Imbue the spear with the flame of frenzy and leap forwards, plunging it into the ground and setting off a maddening explosion.<<NEWLINE>>The skill inflicts both the enemy and the user with madness."),
		(1051,"Unique Skill: Miquella's Ring of Light<<NEWLINE>><<NEWLINE>>Summon Miquella's shining halo and fire it forwards.<<NEWLINE>>Can be fired in rapid succession."),
		(1052,"Unique Skill: Golden Tempering<<NEWLINE>><<NEWLINE>>Cross the two swords to grant their attacks holy essence.<<NEWLINE>>While in effect, strong attack performs a dual-wielding combo attack."),
		(1053,"Unique Skill: Last Rites<<NEWLINE>><<NEWLINE>>Raise the epitaph to grant the effect of Sacred Order to yourself and allies in the vicinity.<<NEWLINE>>Particularly effective at laying to rest Those Who Live in Death."),
		(1054,"Unique Skill: Unblockable Blade<<NEWLINE>><<NEWLINE>>Imbue the cipher blade with light, extending its length, then strike with a sudden sweeping attack.<<NEWLINE>>This attack cannot be blocked."),
		(1055,"Unique Skill: Eochaid's Dancing Blade<<NEWLINE>><<NEWLINE>>Infuse the sword with energy, then fling it forwards in a corkscrew attack. The sword continuously deals damage while violently spinning.<<NEWLINE>>Charge the attack to increase reach and duration of the spin."),
		(1167,"Unique Skill: Corpse Wax Cutter<<NEWLINE>><<NEWLINE>>Lost skill of ancient heroes.<<NEWLINE>>Lift the sword up high to release the power of corpse wax and launch it forwards as a blade-like projectile.<<NEWLINE>>"),
		(1168,"Unique Skill: Zamor Ice Storm<<NEWLINE>><<NEWLINE>>Plunge the curved sword into the ground, building power before unleashing a freezing storm that batters the surroundings."),
		(1169,"Unique Skill: Radahn's Rain<<NEWLINE>><<NEWLINE>>Archery skill performed from a low stance.<<NEWLINE>>Ready the bow and fire a sudden flurry of arrows up into the sky. The arrows will pour on foes like rain."),
		(1170,"Unique Skill: The Queen's Black Flame<<NEWLINE>><<NEWLINE>>Set the blade ablaze with the god-slaying black flame before delivering a sweeping slash. Additional input allows for a follow-up attack. The black flames will continue to wear down HP for a while."),
		(1171,"Unique Skill: Dynast's Finesse<<NEWLINE>><<NEWLINE>>Nimbly avoid an attack, securing some distance from foes. Follow up with strong attack to perform a sudden lunge, and press strong attack again to perform a sweeping slice."),
		(1172,"Unique Skill: Magma Shower<<NEWLINE>><<NEWLINE>>Slash at foes in a twirling motion while scattering magma all around.<<NEWLINE>>Additional input allows for a follow-up attack."),
		(1173,"Unique Skill: Nebula<<NEWLINE>><<NEWLINE>>Imbue the Naturalborn's wings with magic to send forth a dark cloud of stars that lingers briefly before exploding."),
		(1174,"Unique Skill: Death Flare<<NEWLINE>><<NEWLINE>>Set the lusterless sun ablaze with the Prince of Death's flames, inflicting the death ailment upon foes.<<NEWLINE>>Follow up with an additional input to bring down the armament, triggering an explosion."),
		(1175,"Unique Skill: Bloodhound's Finesse<<NEWLINE>><<NEWLINE>>Slash upwards with the Bloodhound's Fang, using the momentum of the strike to perform a backwards somersault and gain some distance from foes. Follow up with a strong attack to perform the Bloodhound's Step attack."),
		(1176,"Unique Skill: Magma Guillotine<<NEWLINE>><<NEWLINE>>Grab the scalesword with both hands, as a wyrm would hold it in its mouth, and leap forwards, smashing it into the ground and triggering a blast of magma. Follow up with an additional input to perform a chopping attack."),
		(1177,"Unique Skill: Corpse Piler<<NEWLINE>><<NEWLINE>>Forms a blade of cursed blood for repeated, interweaving successive attacks. Follow up with an additional input for further successive attacks."),
		(1178,"Unique Skill: Transient Moonlight<<NEWLINE>><<NEWLINE>>Sheathe blade, holding it at the hip in a composed stance.<<NEWLINE>>Follow up with either a normal or a strong attack to draw the blade at great speed for an instant slash attack. Both attacks fire off a wave of light."),
		(1179,"Unique Skill: Bloodblade Dance<<NEWLINE>><<NEWLINE>>Leap at foe to perform a flurry of tornado-like attacks.<<NEWLINE>>Follow up with an additional input to perform an attack that ends in an evasive maneuver."),
		(1180,"Skill: Death Monarch<<NEWLINE>><<NEWLINE>>Launch summoned death monarchs at enemies,<<NEWLINE>>siphoning HP from those hit and returning<<NEWLINE>>it to the caster."),
		(1181,"Skill: Miquella's Hidden Blade<<NEWLINE>><<NEWLINE>>Conjures a blade blessed with Miquella's protection, and performs an attack that is highly damaging against those who live in death."),
		(1182,"Unique Skill: Knowledge Above All<<NEWLINE>><<NEWLINE>>Raise the scepter to manifest the realm of the All-Knowing. Enemy magic and holy damage negation will be reduced for all within the area, including the caster."),
		(1183,"Unique Skill: Devourer of Worlds<<NEWLINE>><<NEWLINE>>Charge the scepter with magic and strike it against the ground to steal the HP of all nearby enemies."),
		(1184,"Unique Skill: Familial Rancor<<NEWLINE>><<NEWLINE>>Gently rattle the copper heads to summon vengeful spirits that chase down foes.<<NEWLINE>>The anguish of a spouse and children invites accursed wrath."),
		(1185,"Unique Skill: Rosus's Summons<<NEWLINE>><<NEWLINE>>Raise the axe aloft to summon those lost in death.<<NEWLINE>>Three skeletons will appear at a distance and attack in tandem before vanishing."),
		(1186,"Unique Skill: Thunderstorm<<NEWLINE>><<NEWLINE>>Imbue the armament's wing-blade with lightning and swing it around to create a tempestuous lightning storm. Follow up with an additional input to perform up to two spinning attacks.<<NEWLINE>>The lightning will stay on the blade for a while."),
		(1187,"Unique Skill: Sacred Phalanx<<NEWLINE>><<NEWLINE>>Release the power of a hidden incantation to erect a palisade of golden spears frontwards."),
		(1188,"Unique Skill: Great-Serpent Hunt<<NEWLINE>><<NEWLINE>>Perform a powerful forward lunge and follow up with an upward thrust via additional input. When fighting a great serpent, a long blade of light will appear, revealing the armament's true power."),
		(1189,"Unique Skill: Angel's Wings<<NEWLINE>><<NEWLINE>>Jump and imbue the wing-blade of the armament with light, then deliver a slashing attack on the enemy.<<NEWLINE>>The white wings impede recovery actions using a flask of tears."),
		(1190,"Unique Skill: Storm Kick<<NEWLINE>><<NEWLINE>>Thrust the prosthetic leg blade into the ground, creating a storm.<<NEWLINE>>Follow up with a strong attack to perform a lightning-infused jumping attack."),
		(1191,"Unique Skill: Unblockable Blade<<NEWLINE>><<NEWLINE>>Imbue the cipher blade with light, then lunge forward with a sudden piercing attack.<<NEWLINE>>This attack cannot be blocked."),
		(1192,"Unique Skill: Sorcery of the Crozier<<NEWLINE>><<NEWLINE>>Channel magic into the glintstone to activate an ancient sorcery, producing floating magic projectiles that chase enemies automatically."),
		(1193,"Unique Skill: Erdtree Slam<<NEWLINE>><<NEWLINE>>Jump up high into the air and crash down on the ground ahead. The resulting pratfall sends golden shockwaves in all directions.<<NEWLINE>>This is the most powerful of all the Ground Slam skills."),
		(1194,"Unique Skill: Gravity Bolt<<NEWLINE>><<NEWLINE>>Imbue the jaw of the fallingstar beast with gravitational lightning, sending a bolt crashing down a short distance away.<<NEWLINE>>Can be fired in rapid succession."),
		(1195,"Unique Skill: Fires of Slumber<<NEWLINE>><<NEWLINE>>Blow into the candlestick's flame, creating a stream of hazy purple fire to cover the ground ahead.<<NEWLINE>>The intoxicating flames inflict the sleep ailment upon foes."),
		(1196,"Unique Skill: Golden Retaliation<<NEWLINE>><<NEWLINE>>Ready the shield to unleash its protective incantation.<<NEWLINE>>This will dispel sorceries and incantations, retaliating with golden power."),
		(1197,"Unique Skill: Contagious Fury<<NEWLINE>><<NEWLINE>>Incite the jellyfish's wrath and allow its fury to flow through you.<<NEWLINE>>Raises attack power for a certain duration."),
		(1198,"Unique Skill: Ordovis's Vortex<<NEWLINE>><<NEWLINE>>Channel the power of the crucible to spin the entire sword in midair, building momentum before slamming the blade down onto the ground.<<NEWLINE>>This skill can be charged to increase its power."),
		(1199,"Unique Skill: Spinning Weapon<<NEWLINE>><<NEWLINE>>Channel magic into the glintstone to suspend the scepter in mid air and cause it to spin violently.<<NEWLINE>>Those it touches will suffer successive magic attacks."),
])});
