#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_info;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_info_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_info_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod accessory_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod arts_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod arts_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod arts_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod arts_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod arts_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod arts_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_effect;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_effect_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_effect_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_info;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_info_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_info_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod gem_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_dialog;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_dialog_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_dialog_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_info;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_info2;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_info2_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_info2_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_info_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_info_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod goods_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_info;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_info_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_info_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod magic_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod npc_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod npc_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod npc_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod place_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod place_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod place_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_info;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_info_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_info_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod protector_name_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_caption;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_caption_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_caption_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_effect;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_effect_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_effect_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_info;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_info_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_info_dlc02;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_name;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_name_dlc01;
#[allow(unused, non_snake_case, non_camel_case_types)]
pub mod weapon_name_dlc02;
