use std::{collections::HashMap, sync::LazyLock};

pub static WEAPON_EFFECT: LazyLock<HashMap<u32, &'static str>> = LazyLock::new(|| {
    HashMap::from([
		(1,""),
		(2,""),
		(3,""),
		(100,""),
		(1000,"Some damage isn't negated when guarded"),
		(1001,"Recovers HP from defeated enemies"),
		(1002,"Recovers FP from defeated enemies"),
		(1003,"Successful attacks recover HP"),
		(1004,"Successful attacks recover FP"),
		(1005,"Slowly recovers HP"),
		(1006,"Slowly recovers FP"),
		(1007,"Boosts stamina recovery speed"),
		(1008,"Attack power rises as attacks continue"),
		(1009,"Take self-inflicted damage"),
		(1010,"Saps beasts of the will to fight"),
		(1011,""),
		(1012,"Boosts potency of physical spells"),
		(1013,"Boosts potency of fire spells"),
		(1014,"Boosts potency of spirit spells"),
		(1015,"Boosts potency of lightning spells"),
		(1016,"Boosts potency of sacred spells"),
		(1017,"Boosts area of buffs and healing spells"),
		(1018,"Handles any sorcery or incantation"),
		(1019,"Use as catalyst for glintstone sorcery"),
		(1020,"Use as seal for incantations"),
		(1021,"Successive attacks recover HP"),
		(1022,"Successive attacks recover FP"),
		(1100,"Boosts Crystalian sorcery"),
		(1101,"Boosts gravity sorcery"),
		(1102,"Boosts thorn sorcery"),
		(1103,"Boosts death sorcery"),
		(1104,"Boosts full moon sorcery"),
		(1105,"Boosts Stonedigger sorcery"),
		(1106,"Boosts Glintblade sorcery"),
		(1107,"Boosts Carian sword sorcery"),
		(1108,"Boosts Azur's primeval sorcery"),
		(1109,"Boosts Lusat's primeval sorcery"),
		(1110,"Boosts invisibility sorcery"),
		(1111,"Boosts Giants' Flame incantations"),
		(1112,"Boosts Fundamentalist incantations"),
		(1113,"Boosts bestial incantations"),
		(1114,"Boosts Dragon Cult incantations"),
		(1115,"Boosts Dragon Communion incantations"),
		(1116,"Boosts Frenzied Flame incantations"),
		(1117,"Boosts lava sorcery"),
		(1118,"Boosts godslayer incantations"),
		(6400,"Causes slight poison buildup (<?poisonATKpwr?>)"),
		(6401,"Causes poison buildup (<?poisonATKpwr?>)"),
		(6402,"Causes heavy poison buildup (<?poisonATKpwr?>)"),
		(6403,""),
		(6404,""),
		(6405,""),
		(6406,""),
		(6407,""),
		(6408,""),
		(6409,""),
		(6410,"Causes intense poison buildup (<?poisonATKpwr?>)"),
		(6450,"Causes slight scarlet rot buildup (<?diseaseATKpwr?>)"),
		(6451,"Causes scarlet rot buildup (<?diseaseATKpwr?>)"),
		(6452,"Causes heavy scarlet rot buildup (<?diseaseATKpwr?>)"),
		(6500,"Causes slight blood loss buildup (<?bleedATKpwr?>)"),
		(6501,"Causes blood loss buildup (<?bleedATKpwr?>)"),
		(6502,"Causes heavy blood loss buildup (<?bleedATKpwr?>)"),
		(6503,""),
		(6504,""),
		(6505,""),
		(6506,""),
		(6507,""),
		(6508,""),
		(6509,""),
		(6510,"Causes intense blood loss buildup (<?bleedATKpwr?>)"),
		(6550,"Causes slight death buildup (<?curseATKpwr?>)"),
		(6551,"Causes death buildup (<?curseATKpwr?>)"),
		(6552,"Causes heavy death buildup (<?curseATKpwr?>)"),
		(6600,"Causes slight frost buildup (<?freezeATKpwr?>)"),
		(6601,"Causes frost buildup (<?freezeATKpwr?>)"),
		(6602,"Causes heavy frost buildup (<?freezeATKpwr?>)"),
		(6650,"Causes slight sleep buildup (<?sleepATKpwr?>)"),
		(6651,"Causes sleep buildup (<?sleepATKpwr?>)"),
		(6652,"Causes heavy sleep buildup (<?sleepATKpwr?>)"),
		(6700,"Causes slight madness buildup (<?madnessATKpwr?>)"),
		(6701,"Causes madness buildup (<?madnessATKpwr?>)"),
		(6702,"Causes heavy madness buildup (<?madnessATKpwr?>)"),
])});
